// Code generated by tools/modbitgen from contracts/settings/*.yaml. DO NOT EDIT.
//
// Edit the contract and run "make generate". The drift gate in "make check" fails when this file
// is stale.

package settings

// Settings keys. Consume these constants; string literals for settings keys are
// prohibited (R-SET-02).
const (
	// How long a granted approval may be reused before it must be requested again.
	KeyAgentApprovalDuration Key = "agent.approval.duration"

	// Lifetime of a pending approval request before it expires (SFX-3).
	KeyAgentApprovalExpirationSeconds Key = "agent.approval.expiration_seconds"

	// Lowest side-effect class that requires two distinct human approvers.
	KeyAgentApprovalTwoPersonThreshold Key = "agent.approval.two_person_threshold"

	// Create an isolated git worktree for each Code run.
	KeyAgentAutoCreateWorktree Key = "agent.auto_create_worktree"

	// Require the Verify workflow to pass before a run may report completion.
	KeyAgentAutoVerifyBeforeCompletion Key = "agent.auto_verify_before_completion"

	// Workflow mode a new session starts in.
	KeyAgentDefaultMode Key = "agent.default_mode"

	// Agent Profile id applied when a run does not name one.
	KeyAgentDefaultProfile Key = "agent.default_profile"

	// Controls when agent tool calls require approval.
	KeyAgentExecutionMode Key = "agent.execution.mode"

	// Maximum concurrent agent runs attributable to one actor.
	KeyAgentMaxParallelRuns Key = "agent.max_parallel_runs"

	// Maximum subagent nesting depth (ORC-2).
	KeyAgentMaxSubagentDepth Key = "agent.max_subagent_depth"

	// Require an approved plan before a Code run may mutate the workspace.
	KeyAgentPlanBeforeCode Key = "agent.plan_before_code"

	// Maximum self-correction attempts per failing step (COR-5).
	KeyAgentRetryLimit Key = "agent.retry_limit"

	// Tool identifiers a run may invoke. Scopes intersect; lower scopes cannot widen.
	KeyAgentToolsAllowed Key = "agent.tools.allowed"

	// Tool identifiers no run may invoke. Denials from every scope are unioned.
	KeyAgentToolsDenied Key = "agent.tools.denied"

	// Build and maintain local retrieval indexes for registered sources.
	KeyContextIndexingEnabled Key = "context.indexing.enabled"

	// Additional exclusion patterns, unioned across scopes. `.modbit/` holds Modbit's own state,
	// including index snapshots; indexing it would make each scan record the previous scan's output as
	// repository content. The union merge means no scope can remove that exclusion.
	KeyContextIndexingExcludedGlobs Key = "context.indexing.excluded_globs"

	// Where index segments are built and stored. Local is the most restrictive boundary.
	KeyContextIndexingLocation Key = "context.indexing.location"

	// Files larger than this are referenced but not parsed or embedded.
	KeyContextIndexingMaxFileBytes Key = "context.indexing.max_file_bytes"

	// Exclude gitignored paths from indexing and retrieval.
	KeyContextIndexingRespectGitignore Key = "context.indexing.respect_gitignore"

	// Token budget for one assembled context pack.
	KeyContextRetrievalBudgetTokens Key = "context.retrieval.budget_tokens"

	// Number of candidates passed to reranking before token-budget packing.
	KeyContextRetrievalRerankDepth Key = "context.retrieval.rerank_depth"

	// Include clipboard contents. Requires explicit opt-in at every use.
	KeyContextSourcesClipboard Key = "context.sources.clipboard"

	// Context source kinds eligible for retrieval. Scopes intersect so an administrator can remove a
	// source class that a user cannot restore.
	KeyContextSourcesEnabled Key = "context.sources.enabled"

	// Include terminal selections and recent commands in retrieval. Off by default because shell
	// history is a common secret-bearing surface (INV-11).
	KeyContextSourcesTerminalHistory Key = "context.sources.terminal_history"

	// Explicit escape hatch. Every entry is audited on use; empty is the safe default.
	KeyExecutionCommandsOutsideSandbox Key = "execution.commands_outside_sandbox"

	// Handling for commands classified as destructive or privilege changing.
	KeyExecutionDangerousCommands Key = "execution.dangerous_commands"

	// Paths no tool may read or write regardless of write roots.
	KeyExecutionFilesystemProtectedPaths Key = "execution.filesystem.protected_paths"

	// Absolute or workspace-relative roots the sandbox may write to.
	KeyExecutionFilesystemWriteRoots Key = "execution.filesystem.write_roots"

	// Memory ceiling for a single sandboxed process.
	KeyExecutionLimitsMemoryMb Key = "execution.limits.memory_mb"

	// Wall-clock ceiling for a single sandboxed process.
	KeyExecutionLimitsWallTimeSeconds Key = "execution.limits.wall_time_seconds"

	// Domains reachable in allowlist mode. Scopes intersect.
	KeyExecutionNetworkAllowedDomains Key = "execution.network.allowed_domains"

	// Domains never reachable, overriding any allowlist.
	KeyExecutionNetworkDeniedDomains Key = "execution.network.denied_domains"

	// Egress posture for sandboxed processes.
	KeyExecutionNetworkMode Key = "execution.network.mode"

	// Run tool execution inside a SandboxBackend.
	KeyExecutionSandboxEnabled Key = "execution.sandbox.enabled"

	// Refuse execution when a mandatory sandbox control cannot be established (SBX-6).
	KeyExecutionSandboxFailClosed Key = "execution.sandbox.fail_closed"

	// Minimum isolation strength a backend must report to be eligible (SBX-4).
	KeyExecutionSandboxMinIsolation Key = "execution.sandbox.min_isolation"

	// Allow the gateway to select a route within the policy envelope.
	KeyModelAdaptiveRouterEnabled Key = "model.adaptive_router.enabled"

	// Model capability aliases eligible for routing.
	KeyModelAliasesAllowed Key = "model.aliases.allowed"

	// Upper bound on prompt tokens assembled for one model call.
	KeyModelContextWindowCapTokens Key = "model.context_window_cap_tokens"

	// Per-run inference spend ceiling in micro-units of the reporting currency.
	KeyModelCostCapPerRunMicros Key = "model.cost_cap_per_run_micros"

	// Prefer local inference endpoints when they satisfy required capabilities.
	KeyModelLocalFirst Key = "model.local_first"

	// Ceiling on provider reasoning controls where the provider exposes them.
	KeyModelMaxReasoningEffort Key = "model.max_reasoning_effort"

	// Alias-to-revision pins that hold a route at a verified provider revision (MOD-5).
	KeyModelPinnedRevisions Key = "model.pinned_revisions"

	// Prompt and completion body capture. Metadata-only is the product default (INV-4).
	KeyModelPromptBodyLogging Key = "model.prompt_body_logging"

	// Provider ids eligible for routing. Scopes intersect; lower scopes cannot widen.
	KeyModelProvidersAllowed Key = "model.providers.allowed"

	// Regions a route must satisfy. Empty means no residency constraint.
	KeyModelResidencyRequiredRegions Key = "model.residency.required_regions"

	// Maximum provider-side retention a route may have. Zero requires zero retention.
	KeyModelRetentionMaxProviderDays Key = "model.retention.max_provider_days"

	// Permit authorized declassification of tainted content (TNT-2).
	KeyTaintDeclassificationAllowed Key = "taint.declassification.allowed"

	// Lowest role that may record a declassification with actor and rationale.
	KeyTaintDeclassificationMinRole Key = "taint.declassification.min_role"

	// Enforce provenance taint as a policy dimension (TNT-3).
	KeyTaintEnforcementEnabled Key = "taint.enforcement.enabled"

	// Side-effect classes subject to taint escalation.
	KeyTaintEscalationSideEffectClasses Key = "taint.escalation.side_effect_classes"

	// Provenance classes that escalate approval class for externally compensatable and externally
	// irreversible operations (TNT-4). Scopes union; a class can be added but not removed by a lower
	// scope.
	KeyTaintEscalationTriggerClasses Key = "taint.escalation.trigger_classes"

	// Honour the TNT-4 carve-out for operations declared in the approved plan before the taint
	// entered. Setting false removes the carve-out and is strictly more restrictive.
	KeyTaintPlanDeclarationExemptsEscalation Key = "taint.plan_declaration.exempts_escalation"

	// Class assigned to content whose provenance cannot be verified (TNT-6). The default resolves to
	// the highest-risk registered class; the alternatives exist only to pin a specific class for audit
	// clarity and can never resolve lower than the pinned value.
	KeyTaintUnknownProvenanceClass Key = "taint.unknown_provenance.class"
)

// definitions is the generated Settings Registry. NewRegistry copies it.
var definitions = []Definition{
	{
		Key:              "agent.approval.duration",
		Namespace:        "agent",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"once", "session", "repository", "permanent"},
		Default:          "session",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeUser, ScopeSession},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"once", "session", "repository", "permanent"},
		ChangeEffect:     EffectImmediate,
		SecurityClass:    SecurityHigh,
		Description:      "How long a granted approval may be reused before it must be requested again.",
		UI:               UI{Label: "Duration", Group: "approval", Order: 11, Widget: WidgetSelect},
	},
	{
		Key:           "agent.approval.expiration_seconds",
		Namespace:     "agent",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(900),
		Min:           ptrInt64(30),
		Max:           ptrInt64(86400),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeUser},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectImmediate,
		SecurityClass: SecurityHigh,
		Description:   "Lifetime of a pending approval request before it expires (SFX-3).",
		UI:            UI{Label: "Expiration seconds", Group: "approval", Order: 13, Widget: WidgetNumber},
	},
	{
		Key:              "agent.approval.two_person_threshold",
		Namespace:        "agent",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"never", "externally_irreversible", "externally_compensatable", "locally_destructive"},
		Default:          "never",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"locally_destructive", "externally_compensatable", "externally_irreversible", "never"},
		ChangeEffect:     EffectNextToolCall,
		SecurityClass:    SecurityCritical,
		Description:      "Lowest side-effect class that requires two distinct human approvers.",
		UI:               UI{Label: "Two person threshold", Group: "approval", Order: 12, Widget: WidgetSelect},
	},
	{
		Key:           "agent.auto_create_worktree",
		Namespace:     "agent",
		SchemaVersion: 1,
		Type:          TypeBool,
		Default:       true,
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeUser, ScopeDevice, ScopeRepositoryLocal},
		Merge:         MergeOverride,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityLow,
		Description:   "Create an isolated git worktree for each Code run.",
		UI:            UI{Label: "Auto create worktree", Group: "agent", Order: 8, Widget: WidgetToggle},
	},
	{
		Key:              "agent.auto_verify_before_completion",
		Namespace:        "agent",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          true,
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{true, false},
		ChangeEffect:     EffectNextRun,
		SecurityClass:    SecurityHigh,
		Description:      "Require the Verify workflow to pass before a run may report completion.",
		UI:               UI{Label: "Auto verify before completion", Group: "agent", Order: 7, Widget: WidgetToggle},
	},
	{
		Key:           "agent.default_mode",
		Namespace:     "agent",
		SchemaVersion: 1,
		Type:          TypeEnum,
		Enum:          []string{"ask", "plan", "code", "debug", "review", "verify"},
		Default:       "ask",
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeRepositoryLocal, ScopeSession},
		Merge:         MergeOverride,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityLow,
		Description:   "Workflow mode a new session starts in.",
		UI:            UI{Label: "Default mode", Group: "agent", Order: 1, Widget: WidgetSelect},
	},
	{
		Key:           "agent.default_profile",
		Namespace:     "agent",
		SchemaVersion: 1,
		Type:          TypeString,
		Default:       "",
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeUser, ScopeRepositoryLocal, ScopeSession},
		Merge:         MergeOverride,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityMedium,
		Description:   "Agent Profile id applied when a run does not name one.",
		UI:            UI{Label: "Default profile", Group: "agent", Order: 2, Widget: WidgetText},
	},
	{
		Key:              "agent.execution.mode",
		Namespace:        "agent",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"manual", "allowlist", "auto-review", "unrestricted"},
		Default:          "auto-review",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile, ScopeUser, ScopeDevice, ScopeRepositoryLocal, ScopeSession},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"manual", "allowlist", "auto-review", "unrestricted"},
		ChangeEffect:     EffectNextToolCall,
		SecurityClass:    SecurityHigh,
		Description:      "Controls when agent tool calls require approval.",
		UI:               UI{Label: "Mode", Group: "execution", Order: 0, Widget: WidgetSelect},
	},
	{
		Key:           "agent.max_parallel_runs",
		Namespace:     "agent",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(4),
		Min:           ptrInt64(1),
		Max:           ptrInt64(64),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeUser, ScopeDevice, ScopeSession},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityMedium,
		Description:   "Maximum concurrent agent runs attributable to one actor.",
		UI:            UI{Label: "Max parallel runs", Group: "agent", Order: 4, Widget: WidgetNumber},
	},
	{
		Key:           "agent.max_subagent_depth",
		Namespace:     "agent",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(2),
		Min:           ptrInt64(0),
		Max:           ptrInt64(8),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeSession},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityHigh,
		Description:   "Maximum subagent nesting depth (ORC-2).",
		UI:            UI{Label: "Max subagent depth", Group: "agent", Order: 5, Widget: WidgetNumber},
	},
	{
		Key:              "agent.plan_before_code",
		Namespace:        "agent",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          true,
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{true, false},
		ChangeEffect:     EffectNextRun,
		SecurityClass:    SecurityMedium,
		Description:      "Require an approved plan before a Code run may mutate the workspace.",
		UI:               UI{Label: "Plan before code", Group: "agent", Order: 3, Widget: WidgetToggle},
	},
	{
		Key:           "agent.retry_limit",
		Namespace:     "agent",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(3),
		Min:           ptrInt64(0),
		Max:           ptrInt64(10),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityMedium,
		Description:   "Maximum self-correction attempts per failing step (COR-5).",
		UI:            UI{Label: "Retry limit", Group: "agent", Order: 6, Widget: WidgetNumber},
	},
	{
		Key:           "agent.tools.allowed",
		Namespace:     "agent",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{"*"},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile},
		Merge:         MergeIntersection,
		ChangeEffect:  EffectNextToolCall,
		SecurityClass: SecurityCritical,
		Description:   "Tool identifiers a run may invoke. Scopes intersect; lower scopes cannot widen.",
		UI:            UI{Label: "Allowed", Group: "tools", Order: 10, Widget: WidgetList},
	},
	{
		Key:           "agent.tools.denied",
		Namespace:     "agent",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:         MergeUnionDeny,
		ChangeEffect:  EffectNextToolCall,
		SecurityClass: SecurityCritical,
		Description:   "Tool identifiers no run may invoke. Denials from every scope are unioned.",
		UI:            UI{Label: "Denied", Group: "tools", Order: 9, Widget: WidgetList},
	},
	{
		Key:           "context.indexing.enabled",
		Namespace:     "context",
		SchemaVersion: 1,
		Type:          TypeBool,
		Default:       true,
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeUser, ScopeDevice, ScopeRepositoryLocal},
		Merge:         MergeOverride,
		ChangeEffect:  EffectNextIndex,
		SecurityClass: SecurityMedium,
		Description:   "Build and maintain local retrieval indexes for registered sources.",
		UI:            UI{Label: "Enabled", Group: "indexing", Order: 0, Widget: WidgetToggle},
	},
	{
		Key:           "context.indexing.excluded_globs",
		Namespace:     "context",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{"**/.modbit/**", "**/node_modules/**", "**/target/**", "**/.venv/**", "**/dist/**"},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeRepositoryLocal},
		Merge:         MergeUnion,
		ChangeEffect:  EffectNextIndex,
		SecurityClass: SecurityMedium,
		Description:   "Additional exclusion patterns, unioned across scopes. `.modbit/` holds Modbit's own state, including index snapshots; indexing it would make each scan record the previous scan's output as repository content. The union merge means no scope can remove that exclusion.",
		UI:            UI{Label: "Excluded globs", Group: "indexing", Order: 4, Widget: WidgetList},
	},
	{
		Key:              "context.indexing.location",
		Namespace:        "context",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"local", "remote", "hybrid"},
		Default:          "local",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeDevice},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"local", "hybrid", "remote"},
		ChangeEffect:     EffectNextIndex,
		SecurityClass:    SecurityCritical,
		Description:      "Where index segments are built and stored. Local is the most restrictive boundary.",
		UI:               UI{Label: "Location", Group: "indexing", Order: 1, Widget: WidgetSelect},
	},
	{
		Key:           "context.indexing.max_file_bytes",
		Namespace:     "context",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(1048576),
		Min:           ptrInt64(1024),
		Max:           ptrInt64(268435456),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeRepositoryLocal},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextIndex,
		SecurityClass: SecurityLow,
		Description:   "Files larger than this are referenced but not parsed or embedded.",
		UI:            UI{Label: "Max file bytes", Group: "indexing", Order: 2, Widget: WidgetNumber},
	},
	{
		Key:              "context.indexing.respect_gitignore",
		Namespace:        "context",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          true,
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeUser, ScopeRepositoryLocal},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{true, false},
		ChangeEffect:     EffectNextIndex,
		SecurityClass:    SecurityHigh,
		Description:      "Exclude gitignored paths from indexing and retrieval.",
		UI:               UI{Label: "Respect gitignore", Group: "indexing", Order: 3, Widget: WidgetToggle},
	},
	{
		Key:           "context.retrieval.budget_tokens",
		Namespace:     "context",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(32000),
		Min:           ptrInt64(512),
		Max:           ptrInt64(2000000),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityLow,
		Description:   "Token budget for one assembled context pack.",
		UI:            UI{Label: "Budget tokens", Group: "retrieval", Order: 5, Widget: WidgetNumber},
	},
	{
		Key:           "context.retrieval.rerank_depth",
		Namespace:     "context",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(50),
		Min:           ptrInt64(1),
		Max:           ptrInt64(500),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeSession},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityLow,
		Description:   "Number of candidates passed to reranking before token-budget packing.",
		UI:            UI{Label: "Rerank depth", Group: "retrieval", Order: 6, Widget: WidgetNumber},
	},
	{
		Key:              "context.sources.clipboard",
		Namespace:        "context",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          false,
		Scopes:           []Scope{ScopeUser, ScopeDevice, ScopeSession},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{false, true},
		ChangeEffect:     EffectImmediate,
		SecurityClass:    SecurityCritical,
		Description:      "Include clipboard contents. Requires explicit opt-in at every use.",
		UI:               UI{Label: "Clipboard", Group: "sources", Order: 9, Widget: WidgetToggle},
	},
	{
		Key:           "context.sources.enabled",
		Namespace:     "context",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{"current_file", "open_files", "selection", "recent_edits", "git_diff", "diagnostics", "codewiki"},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:         MergeIntersection,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityHigh,
		Description:   "Context source kinds eligible for retrieval. Scopes intersect so an administrator can remove a source class that a user cannot restore.",
		UI:            UI{Label: "Enabled", Group: "sources", Order: 7, Widget: WidgetList},
	},
	{
		Key:              "context.sources.terminal_history",
		Namespace:        "context",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          false,
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeUser, ScopeDevice, ScopeRepositoryLocal},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{false, true},
		ChangeEffect:     EffectNextRun,
		SecurityClass:    SecurityCritical,
		Description:      "Include terminal selections and recent commands in retrieval. Off by default because shell history is a common secret-bearing surface (INV-11).",
		UI:               UI{Label: "Terminal history", Group: "sources", Order: 8, Widget: WidgetToggle},
	},
	{
		Key:           "execution.commands_outside_sandbox",
		Namespace:     "execution",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:         MergeIntersection,
		ChangeEffect:  EffectNextToolCall,
		SecurityClass: SecurityCritical,
		Description:   "Explicit escape hatch. Every entry is audited on use; empty is the safe default.",
		UI:            UI{Label: "Commands outside sandbox", Group: "execution", Order: 11, Widget: WidgetList},
	},
	{
		Key:              "execution.dangerous_commands",
		Namespace:        "execution",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"deny", "approve", "allow"},
		Default:          "approve",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile, ScopeRepositoryLocal},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"deny", "approve", "allow"},
		ChangeEffect:     EffectNextToolCall,
		SecurityClass:    SecurityCritical,
		Description:      "Handling for commands classified as destructive or privilege changing.",
		UI:               UI{Label: "Dangerous commands", Group: "execution", Order: 10, Widget: WidgetSelect},
	},
	{
		Key:           "execution.filesystem.protected_paths",
		Namespace:     "execution",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{"**/.git/**", "**/.ssh/**", "**/.aws/**", "**/*.pem", "**/*.key"},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile, ScopeRepositoryLocal},
		Merge:         MergeUnionDeny,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityCritical,
		Description:   "Paths no tool may read or write regardless of write roots.",
		UI:            UI{Label: "Protected paths", Group: "filesystem", Order: 4, Widget: WidgetList},
	},
	{
		Key:           "execution.filesystem.write_roots",
		Namespace:     "execution",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{"${workspace}"},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile, ScopeRepositoryLocal},
		Merge:         MergeIntersection,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityCritical,
		Description:   "Absolute or workspace-relative roots the sandbox may write to.",
		UI:            UI{Label: "Write roots", Group: "filesystem", Order: 3, Widget: WidgetList},
	},
	{
		Key:           "execution.limits.memory_mb",
		Namespace:     "execution",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(4096),
		Min:           ptrInt64(64),
		Max:           ptrInt64(1048576),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeDevice},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityMedium,
		Description:   "Memory ceiling for a single sandboxed process.",
		UI:            UI{Label: "Memory MB", Group: "limits", Order: 9, Widget: WidgetNumber},
	},
	{
		Key:           "execution.limits.wall_time_seconds",
		Namespace:     "execution",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(1800),
		Min:           ptrInt64(1),
		Max:           ptrInt64(86400),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeSession},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityHigh,
		Description:   "Wall-clock ceiling for a single sandboxed process.",
		UI:            UI{Label: "Wall time seconds", Group: "limits", Order: 8, Widget: WidgetNumber},
	},
	{
		Key:           "execution.network.allowed_domains",
		Namespace:     "execution",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile},
		Merge:         MergeIntersection,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityCritical,
		Description:   "Domains reachable in allowlist mode. Scopes intersect.",
		UI:            UI{Label: "Allowed domains", Group: "network", Order: 6, Widget: WidgetList},
	},
	{
		Key:           "execution.network.denied_domains",
		Namespace:     "execution",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile, ScopeRepositoryLocal},
		Merge:         MergeUnionDeny,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityCritical,
		Description:   "Domains never reachable, overriding any allowlist.",
		UI:            UI{Label: "Denied domains", Group: "network", Order: 7, Widget: WidgetList},
	},
	{
		Key:              "execution.network.mode",
		Namespace:        "execution",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"none", "allowlist", "proxy", "open"},
		Default:          "allowlist",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"none", "allowlist", "proxy", "open"},
		ChangeEffect:     EffectNextRun,
		SecurityClass:    SecurityCritical,
		Description:      "Egress posture for sandboxed processes.",
		UI:               UI{Label: "Mode", Group: "network", Order: 5, Widget: WidgetSelect},
	},
	{
		Key:              "execution.sandbox.enabled",
		Namespace:        "execution",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          true,
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeRepository, ScopeAgentProfile, ScopeUser, ScopeDevice},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{true, false},
		ChangeEffect:     EffectNextRun,
		SecurityClass:    SecurityCritical,
		Description:      "Run tool execution inside a SandboxBackend.",
		UI:               UI{Label: "Enabled", Group: "sandbox", Order: 0, Widget: WidgetToggle},
	},
	{
		Key:              "execution.sandbox.fail_closed",
		Namespace:        "execution",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          true,
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{true, false},
		ChangeEffect:     EffectNextRun,
		SecurityClass:    SecurityCritical,
		Description:      "Refuse execution when a mandatory sandbox control cannot be established (SBX-6).",
		UI:               UI{Label: "Fail closed", Group: "sandbox", Order: 1, Widget: WidgetToggle},
	},
	{
		Key:              "execution.sandbox.min_isolation",
		Namespace:        "execution",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"none", "process", "container", "microvm"},
		Default:          "process",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"microvm", "container", "process", "none"},
		ChangeEffect:     EffectNextRun,
		SecurityClass:    SecurityCritical,
		Description:      "Minimum isolation strength a backend must report to be eligible (SBX-4).",
		UI:               UI{Label: "Min isolation", Group: "sandbox", Order: 2, Widget: WidgetSelect},
	},
	{
		Key:           "model.adaptive_router.enabled",
		Namespace:     "model",
		SchemaVersion: 1,
		Type:          TypeBool,
		Default:       true,
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:         MergeOverride,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityMedium,
		Description:   "Allow the gateway to select a route within the policy envelope.",
		UI:            UI{Label: "Enabled", Group: "adaptive_router", Order: 3, Widget: WidgetToggle},
	},
	{
		Key:           "model.aliases.allowed",
		Namespace:     "model",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{"*"},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:         MergeIntersection,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityHigh,
		Description:   "Model capability aliases eligible for routing.",
		UI:            UI{Label: "Allowed", Group: "aliases", Order: 1, Widget: WidgetList},
	},
	{
		Key:           "model.context_window_cap_tokens",
		Namespace:     "model",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(200000),
		Min:           ptrInt64(1024),
		Max:           ptrInt64(10000000),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityMedium,
		Description:   "Upper bound on prompt tokens assembled for one model call.",
		UI:            UI{Label: "Context window cap tokens", Group: "model", Order: 5, Widget: WidgetNumber},
	},
	{
		Key:           "model.cost_cap_per_run_micros",
		Namespace:     "model",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(5000000),
		Min:           ptrInt64(0),
		Max:           ptrInt64(100000000000),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityHigh,
		Description:   "Per-run inference spend ceiling in micro-units of the reporting currency.",
		UI:            UI{Label: "Cost cap per run micros", Group: "model", Order: 6, Widget: WidgetNumber},
	},
	{
		Key:           "model.local_first",
		Namespace:     "model",
		SchemaVersion: 1,
		Type:          TypeBool,
		Default:       false,
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeDevice, ScopeSession},
		Merge:         MergeOverride,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityMedium,
		Description:   "Prefer local inference endpoints when they satisfy required capabilities.",
		UI:            UI{Label: "Local first", Group: "model", Order: 2, Widget: WidgetToggle},
	},
	{
		Key:              "model.max_reasoning_effort",
		Namespace:        "model",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"none", "low", "medium", "high"},
		Default:          "medium",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile, ScopeUser, ScopeSession},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"none", "low", "medium", "high"},
		ChangeEffect:     EffectNextRun,
		SecurityClass:    SecurityMedium,
		Description:      "Ceiling on provider reasoning controls where the provider exposes them.",
		UI:               UI{Label: "Max reasoning effort", Group: "model", Order: 4, Widget: WidgetSelect},
	},
	{
		Key:           "model.pinned_revisions",
		Namespace:     "model",
		SchemaVersion: 1,
		Type:          TypeObject,
		Default:       map[string]any{},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile},
		Merge:         MergeDeepMerge,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityHigh,
		Description:   "Alias-to-revision pins that hold a route at a verified provider revision (MOD-5).",
		UI:            UI{Label: "Pinned revisions", Group: "model", Order: 9, Widget: WidgetJSON},
	},
	{
		Key:              "model.prompt_body_logging",
		Namespace:        "model",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"off", "metadata_only", "redacted", "full"},
		Default:          "metadata_only",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"off", "metadata_only", "redacted", "full"},
		ChangeEffect:     EffectImmediate,
		SecurityClass:    SecurityCritical,
		Description:      "Prompt and completion body capture. Metadata-only is the product default (INV-4).",
		UI:               UI{Label: "Prompt body logging", Group: "model", Order: 10, Widget: WidgetSelect},
	},
	{
		Key:           "model.providers.allowed",
		Namespace:     "model",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{"*"},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile},
		Merge:         MergeIntersection,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityCritical,
		Description:   "Provider ids eligible for routing. Scopes intersect; lower scopes cannot widen.",
		UI:            UI{Label: "Allowed", Group: "providers", Order: 0, Widget: WidgetList},
	},
	{
		Key:           "model.residency.required_regions",
		Namespace:     "model",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:         MergeIntersection,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityCritical,
		Description:   "Regions a route must satisfy. Empty means no residency constraint.",
		UI:            UI{Label: "Required regions", Group: "residency", Order: 7, Widget: WidgetList},
	},
	{
		Key:           "model.retention.max_provider_days",
		Namespace:     "model",
		SchemaVersion: 1,
		Type:          TypeInt,
		Default:       int64(0),
		Min:           ptrInt64(0),
		Max:           ptrInt64(3650),
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:         MergeMinimum,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityCritical,
		Description:   "Maximum provider-side retention a route may have. Zero requires zero retention.",
		UI:            UI{Label: "Max provider days", Group: "retention", Order: 8, Widget: WidgetNumber},
	},
	{
		Key:              "taint.declassification.allowed",
		Namespace:        "taint",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          false,
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{false, true},
		ChangeEffect:     EffectImmediate,
		SecurityClass:    SecurityCritical,
		Description:      "Permit authorized declassification of tainted content (TNT-2).",
		UI:               UI{Label: "Allowed", Group: "declassification", Order: 4, Widget: WidgetToggle},
	},
	{
		Key:              "taint.declassification.min_role",
		Namespace:        "taint",
		SchemaVersion:    1,
		Type:             TypeEnum,
		Enum:             []string{"owner", "security_admin", "space_admin", "maintainer"},
		Default:          "security_admin",
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{"owner", "security_admin", "space_admin", "maintainer"},
		ChangeEffect:     EffectImmediate,
		SecurityClass:    SecurityCritical,
		Description:      "Lowest role that may record a declassification with actor and rationale.",
		UI:               UI{Label: "Min role", Group: "declassification", Order: 5, Widget: WidgetSelect},
	},
	{
		Key:              "taint.enforcement.enabled",
		Namespace:        "taint",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          true,
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{true, false},
		ChangeEffect:     EffectNextRun,
		SecurityClass:    SecurityCritical,
		Description:      "Enforce provenance taint as a policy dimension (TNT-3).",
		UI:               UI{Label: "Enabled", Group: "enforcement", Order: 0, Widget: WidgetToggle},
	},
	{
		Key:           "taint.escalation.side_effect_classes",
		Namespace:     "taint",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{"externally_compensatable", "externally_irreversible"},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:         MergeUnion,
		ChangeEffect:  EffectNextToolCall,
		SecurityClass: SecurityCritical,
		Description:   "Side-effect classes subject to taint escalation.",
		UI:            UI{Label: "Side effect classes", Group: "escalation", Order: 2, Widget: WidgetList},
	},
	{
		Key:           "taint.escalation.trigger_classes",
		Namespace:     "taint",
		SchemaVersion: 1,
		Type:          TypeStringList,
		Default:       []any{"web", "mcp_result", "repository_untrusted"},
		Scopes:        []Scope{ScopeOrganization, ScopeTeam, ScopeSpace, ScopeAgentProfile},
		Merge:         MergeUnion,
		ChangeEffect:  EffectNextToolCall,
		SecurityClass: SecurityCritical,
		Description:   "Provenance classes that escalate approval class for externally compensatable and externally irreversible operations (TNT-4). Scopes union; a class can be added but not removed by a lower scope.",
		UI:            UI{Label: "Trigger classes", Group: "escalation", Order: 1, Widget: WidgetList},
	},
	{
		Key:              "taint.plan_declaration.exempts_escalation",
		Namespace:        "taint",
		SchemaVersion:    1,
		Type:             TypeBool,
		Default:          true,
		Scopes:           []Scope{ScopeOrganization, ScopeTeam, ScopeSpace},
		Merge:            MergeMostRestrictive,
		RestrictiveOrder: []any{false, true},
		ChangeEffect:     EffectNextToolCall,
		SecurityClass:    SecurityCritical,
		Description:      "Honour the TNT-4 carve-out for operations declared in the approved plan before the taint entered. Setting false removes the carve-out and is strictly more restrictive.",
		UI:               UI{Label: "Exempts escalation", Group: "plan_declaration", Order: 3, Widget: WidgetToggle},
	},
	{
		Key:           "taint.unknown_provenance.class",
		Namespace:     "taint",
		SchemaVersion: 1,
		Type:          TypeEnum,
		Enum:          []string{"highest_risk", "mcp_result", "web", "repository_untrusted"},
		Default:       "highest_risk",
		Scopes:        []Scope{ScopeOrganization},
		Merge:         MergeOverride,
		ChangeEffect:  EffectNextRun,
		SecurityClass: SecurityCritical,
		Description:   "Class assigned to content whose provenance cannot be verified (TNT-6). The default resolves to the highest-risk registered class; the alternatives exist only to pin a specific class for audit clarity and can never resolve lower than the pinned value.",
		UI:            UI{Label: "Class", Group: "unknown_provenance", Order: 6, Widget: WidgetSelect},
	},
}

func ptrInt64(v int64) *int64 { return &v }
