// Code generated by tools/modbitgen from contracts/errors/catalog.yaml. DO NOT EDIT.
//
// Edit the contract and run "make generate".

export const ERROR_CATALOG_VERSION = 1;

export const ErrorCode = {
  // The request was malformed or violated a field constraint.
  INVALID_ARGUMENT: "MODBIT_INVALID_ARGUMENT",
  // The requested API, event, schema, or worker protocol version is not supported.
  UNSUPPORTED_VERSION: "MODBIT_UNSUPPORTED_VERSION",
  // A structured artifact failed validation against its Structured Output Contract.
  CONTRACT_VALIDATION_FAILED: "MODBIT_CONTRACT_VALIDATION_FAILED",
  // No valid credential was presented.
  UNAUTHENTICATED: "MODBIT_UNAUTHENTICATED",
  // The authenticated actor lacks permission for this operation.
  PERMISSION_DENIED: "MODBIT_PERMISSION_DENIED",
  // The referenced resource belongs to a different organization or Space.
  TENANT_MISMATCH: "MODBIT_TENANT_MISMATCH",
  // Operation denied by policy.
  POLICY_DENIED: "MODBIT_POLICY_DENIED",
  // The operation requires human approval before it may proceed.
  APPROVAL_REQUIRED: "MODBIT_APPROVAL_REQUIRED",
  // A required approval was denied or revoked.
  APPROVAL_DENIED: "MODBIT_APPROVAL_DENIED",
  // The operation changed after approval; the prior approval no longer binds (SFX-4).
  APPROVAL_INVALIDATED: "MODBIT_APPROVAL_INVALIDATED",
  // Operation requires elevated approval due to taint state.
  TAINT_ESCALATION_REQUIRED: "MODBIT_TAINT_ESCALATION_REQUIRED",
  // The settings key is not present in the Settings Registry.
  SETTING_UNKNOWN: "MODBIT_SETTING_UNKNOWN",
  // The settings value failed type, enum, or range validation.
  SETTING_INVALID: "MODBIT_SETTING_INVALID",
  // A higher settings scope locks this key; lower scopes cannot change it.
  SETTING_LOCKED: "MODBIT_SETTING_LOCKED",
  // The value falls outside the compiled policy envelope for this key.
  SETTING_POLICY_VIOLATION: "MODBIT_SETTING_POLICY_VIOLATION",
  // The run does not exist or is not visible to the actor.
  RUN_NOT_FOUND: "MODBIT_RUN_NOT_FOUND",
  // The command is not valid for the run's current phase.
  RUN_STATE_INVALID: "MODBIT_RUN_STATE_INVALID",
  // Another transition lease is active for this run (R-EVT-06).
  TRANSITION_LEASE_HELD: "MODBIT_TRANSITION_LEASE_HELD",
  // The event sequence allocated for this run is no longer current.
  SEQUENCE_CONFLICT: "MODBIT_SEQUENCE_CONFLICT",
  // The idempotency key was reused with a different request body.
  IDEMPOTENCY_CONFLICT: "MODBIT_IDEMPOTENCY_CONFLICT",
  // The run, Space, or organization budget is exhausted.
  BUDGET_EXHAUSTED: "MODBIT_BUDGET_EXHAUSTED",
  // The operation was cancelled by an actor or a parent run.
  CANCELLED: "MODBIT_CANCELLED",
  // The operation was superseded by a later instruction or run.
  SUPERSEDED: "MODBIT_SUPERSEDED",
  // The repository revision or unsaved overlay no longer matches the run's snapshot.
  SNAPSHOT_DIVERGED: "MODBIT_SNAPSHOT_DIVERGED",
  // An external effect may have occurred but its receipt is missing; reconcile before retrying.
  EFFECT_RECONCILIATION_REQUIRED: "MODBIT_EFFECT_RECONCILIATION_REQUIRED",
  // One or more retrieval channels are unavailable; the response declares the degradation.
  CONTEXT_DEGRADED: "MODBIT_CONTEXT_DEGRADED",
  // Safe restoration could not be proven; the run entered reversion_incomplete (RCV-7).
  REVERSION_INCOMPLETE: "MODBIT_REVERSION_INCOMPLETE",
  // Evidence below configured adequacy threshold.
  ADEQUACY_THRESHOLD_FAILED: "MODBIT_ADEQUACY_THRESHOLD_FAILED",
  // Completion was claimed without the evidence its completion contract requires.
  EVIDENCE_MISSING: "MODBIT_EVIDENCE_MISSING",
  // Unresolved semantic conflict blocks the operation.
  COORDINATION_CONFLICT: "MODBIT_COORDINATION_CONFLICT",
  // The coordination service is unavailable and the run has registered overlaps (CRC-3).
  COORDINATION_UNAVAILABLE: "MODBIT_COORDINATION_UNAVAILABLE",
  // The outbound payload was blocked by classification or DLP (INV-3).
  DLP_BLOCKED: "MODBIT_DLP_BLOCKED",
  // Classification or DLP could not complete; the gateway failed closed.
  DLP_UNAVAILABLE: "MODBIT_DLP_UNAVAILABLE",
  // No model route satisfies the required capabilities within the policy envelope.
  NO_ELIGIBLE_ROUTE: "MODBIT_NO_ELIGIBLE_ROUTE",
  // The upstream model provider is unavailable or returned a transport failure.
  PROVIDER_UNAVAILABLE: "MODBIT_PROVIDER_UNAVAILABLE",
  // Route held pending canary passage.
  CANARY_HOLD: "MODBIT_CANARY_HOLD",
  // Negotiated capability set does not include the operation.
  CAPABILITY_UNAVAILABLE: "MODBIT_CAPABILITY_UNAVAILABLE",
  // A mandatory sandbox control could not be established; execution failed closed (SBX-6).
  SANDBOX_UNAVAILABLE: "MODBIT_SANDBOX_UNAVAILABLE",
  // The worker or workspace lease expired before the operation completed.
  LEASE_EXPIRED: "MODBIT_LEASE_EXPIRED",
  // No eligible worker is available for the environment requirements.
  WORKER_UNAVAILABLE: "MODBIT_WORKER_UNAVAILABLE",
  // The resource does not exist or is not visible to the actor.
  NOT_FOUND: "MODBIT_NOT_FOUND",
  // The resource changed concurrently; the precondition no longer holds.
  CONFLICT: "MODBIT_CONFLICT",
  // The actor exceeded a rate limit.
  RATE_LIMITED: "MODBIT_RATE_LIMITED",
  // The operation exceeded its deadline.
  TIMEOUT: "MODBIT_TIMEOUT",
  // A dependency is unavailable. The caller may retry within its attempt budget.
  UNAVAILABLE: "MODBIT_UNAVAILABLE",
  // An unexpected internal condition occurred. Details are recorded in the trace only.
  INTERNAL: "MODBIT_INTERNAL",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export interface ErrorSpec {
  readonly code: ErrorCode;
  readonly httpStatus: number;
  readonly retryable: boolean;
  readonly description: string;
  readonly detailKeys: readonly string[];
  readonly deprecated: boolean;
}

export const ERROR_SPECS: Readonly<Record<ErrorCode, ErrorSpec>> = {
  [ErrorCode.INVALID_ARGUMENT]: {
    code: "MODBIT_INVALID_ARGUMENT",
    httpStatus: 400,
    retryable: false,
    description: "The request was malformed or violated a field constraint.",
    detailKeys: ["field", "constraint"],
    deprecated: false,
  },
  [ErrorCode.UNSUPPORTED_VERSION]: {
    code: "MODBIT_UNSUPPORTED_VERSION",
    httpStatus: 400,
    retryable: false,
    description: "The requested API, event, schema, or worker protocol version is not supported.",
    detailKeys: ["requested_version", "supported_versions"],
    deprecated: false,
  },
  [ErrorCode.CONTRACT_VALIDATION_FAILED]: {
    code: "MODBIT_CONTRACT_VALIDATION_FAILED",
    httpStatus: 422,
    retryable: false,
    description: "A structured artifact failed validation against its Structured Output Contract.",
    detailKeys: ["schema_id", "schema_version", "artifact_id", "violation_count"],
    deprecated: false,
  },
  [ErrorCode.UNAUTHENTICATED]: {
    code: "MODBIT_UNAUTHENTICATED",
    httpStatus: 401,
    retryable: false,
    description: "No valid credential was presented.",
    detailKeys: ["scheme"],
    deprecated: false,
  },
  [ErrorCode.PERMISSION_DENIED]: {
    code: "MODBIT_PERMISSION_DENIED",
    httpStatus: 403,
    retryable: false,
    description: "The authenticated actor lacks permission for this operation.",
    detailKeys: ["required_role", "resource_type"],
    deprecated: false,
  },
  [ErrorCode.TENANT_MISMATCH]: {
    code: "MODBIT_TENANT_MISMATCH",
    httpStatus: 403,
    retryable: false,
    description: "The referenced resource belongs to a different organization or Space.",
    detailKeys: ["resource_type"],
    deprecated: false,
  },
  [ErrorCode.POLICY_DENIED]: {
    code: "MODBIT_POLICY_DENIED",
    httpStatus: 403,
    retryable: false,
    description: "Operation denied by policy.",
    detailKeys: ["policy_decision_id", "rule_id", "side_effect_class"],
    deprecated: false,
  },
  [ErrorCode.APPROVAL_REQUIRED]: {
    code: "MODBIT_APPROVAL_REQUIRED",
    httpStatus: 428,
    retryable: false,
    description: "The operation requires human approval before it may proceed.",
    detailKeys: ["policy_decision_id", "approval_id", "approval_class", "side_effect_class"],
    deprecated: false,
  },
  [ErrorCode.APPROVAL_DENIED]: {
    code: "MODBIT_APPROVAL_DENIED",
    httpStatus: 403,
    retryable: false,
    description: "A required approval was denied or revoked.",
    detailKeys: ["policy_decision_id", "approval_id"],
    deprecated: false,
  },
  [ErrorCode.APPROVAL_INVALIDATED]: {
    code: "MODBIT_APPROVAL_INVALIDATED",
    httpStatus: 409,
    retryable: false,
    description: "The operation changed after approval; the prior approval no longer binds (SFX-4).",
    detailKeys: ["approval_id", "expected_operation_hash", "actual_operation_hash", "fence_epoch", "approval_scope"],
    deprecated: false,
  },
  [ErrorCode.TAINT_ESCALATION_REQUIRED]: {
    code: "MODBIT_TAINT_ESCALATION_REQUIRED",
    httpStatus: 428,
    retryable: false,
    description: "Operation requires elevated approval due to taint state.",
    detailKeys: ["policy_decision_id", "approval_class", "escalated_from", "taint_classes", "side_effect_class"],
    deprecated: false,
  },
  [ErrorCode.SETTING_UNKNOWN]: {
    code: "MODBIT_SETTING_UNKNOWN",
    httpStatus: 400,
    retryable: false,
    description: "The settings key is not present in the Settings Registry.",
    detailKeys: ["setting_key"],
    deprecated: false,
  },
  [ErrorCode.SETTING_INVALID]: {
    code: "MODBIT_SETTING_INVALID",
    httpStatus: 400,
    retryable: false,
    description: "The settings value failed type, enum, or range validation.",
    detailKeys: ["setting_key", "setting_scope", "expected_type"],
    deprecated: false,
  },
  [ErrorCode.SETTING_LOCKED]: {
    code: "MODBIT_SETTING_LOCKED",
    httpStatus: 403,
    retryable: false,
    description: "A higher settings scope locks this key; lower scopes cannot change it.",
    detailKeys: ["setting_key", "locked_by_scope"],
    deprecated: false,
  },
  [ErrorCode.SETTING_POLICY_VIOLATION]: {
    code: "MODBIT_SETTING_POLICY_VIOLATION",
    httpStatus: 403,
    retryable: false,
    description: "The value falls outside the compiled policy envelope for this key.",
    detailKeys: ["setting_key", "setting_scope", "envelope_source_scope"],
    deprecated: false,
  },
  [ErrorCode.RUN_NOT_FOUND]: {
    code: "MODBIT_RUN_NOT_FOUND",
    httpStatus: 404,
    retryable: false,
    description: "The run does not exist or is not visible to the actor.",
    detailKeys: ["run_id"],
    deprecated: false,
  },
  [ErrorCode.RUN_STATE_INVALID]: {
    code: "MODBIT_RUN_STATE_INVALID",
    httpStatus: 409,
    retryable: false,
    description: "The command is not valid for the run's current phase.",
    detailKeys: ["run_id", "current_phase", "requested_command"],
    deprecated: false,
  },
  [ErrorCode.TRANSITION_LEASE_HELD]: {
    code: "MODBIT_TRANSITION_LEASE_HELD",
    httpStatus: 409,
    retryable: true,
    description: "Another transition lease is active for this run (R-EVT-06).",
    detailKeys: ["run_id", "lease_expires_at"],
    deprecated: false,
  },
  [ErrorCode.SEQUENCE_CONFLICT]: {
    code: "MODBIT_SEQUENCE_CONFLICT",
    httpStatus: 409,
    retryable: true,
    description: "The event sequence allocated for this run is no longer current.",
    detailKeys: ["run_id", "expected_sequence", "actual_sequence"],
    deprecated: false,
  },
  [ErrorCode.IDEMPOTENCY_CONFLICT]: {
    code: "MODBIT_IDEMPOTENCY_CONFLICT",
    httpStatus: 409,
    retryable: false,
    description: "The idempotency key was reused with a different request body.",
    detailKeys: ["idempotency_key"],
    deprecated: false,
  },
  [ErrorCode.BUDGET_EXHAUSTED]: {
    code: "MODBIT_BUDGET_EXHAUSTED",
    httpStatus: 402,
    retryable: false,
    description: "The run, Space, or organization budget is exhausted.",
    detailKeys: ["budget_id", "budget_scope"],
    deprecated: false,
  },
  [ErrorCode.CANCELLED]: {
    code: "MODBIT_CANCELLED",
    httpStatus: 499,
    retryable: false,
    description: "The operation was cancelled by an actor or a parent run.",
    detailKeys: ["run_id", "cancelled_by"],
    deprecated: false,
  },
  [ErrorCode.SUPERSEDED]: {
    code: "MODBIT_SUPERSEDED",
    httpStatus: 409,
    retryable: false,
    description: "The operation was superseded by a later instruction or run.",
    detailKeys: ["run_id", "superseded_by"],
    deprecated: false,
  },
  [ErrorCode.SNAPSHOT_DIVERGED]: {
    code: "MODBIT_SNAPSHOT_DIVERGED",
    httpStatus: 412,
    retryable: false,
    description: "The repository revision or unsaved overlay no longer matches the run's snapshot.",
    detailKeys: ["run_id", "expected_revision", "actual_revision", "resource_type"],
    deprecated: false,
  },
  [ErrorCode.EFFECT_RECONCILIATION_REQUIRED]: {
    code: "MODBIT_EFFECT_RECONCILIATION_REQUIRED",
    httpStatus: 409,
    retryable: false,
    description: "An external effect may have occurred but its receipt is missing; reconcile before retrying.",
    detailKeys: ["run_id", "step_id", "effect_key", "integration_id"],
    deprecated: false,
  },
  [ErrorCode.CONTEXT_DEGRADED]: {
    code: "MODBIT_CONTEXT_DEGRADED",
    httpStatus: 206,
    retryable: true,
    description: "One or more retrieval channels are unavailable; the response declares the degradation.",
    detailKeys: ["degraded_channels", "healthy_channels", "space_id"],
    deprecated: false,
  },
  [ErrorCode.REVERSION_INCOMPLETE]: {
    code: "MODBIT_REVERSION_INCOMPLETE",
    httpStatus: 409,
    retryable: false,
    description: "Safe restoration could not be proven; the run entered reversion_incomplete (RCV-7).",
    detailKeys: ["run_id", "checkpoint_id", "unresolved_count"],
    deprecated: false,
  },
  [ErrorCode.ADEQUACY_THRESHOLD_FAILED]: {
    code: "MODBIT_ADEQUACY_THRESHOLD_FAILED",
    httpStatus: 422,
    retryable: false,
    description: "Evidence below configured adequacy threshold.",
    detailKeys: ["run_id", "adequacy_method", "score", "threshold"],
    deprecated: false,
  },
  [ErrorCode.EVIDENCE_MISSING]: {
    code: "MODBIT_EVIDENCE_MISSING",
    httpStatus: 422,
    retryable: false,
    description: "Completion was claimed without the evidence its completion contract requires.",
    detailKeys: ["run_id", "contract_id", "missing_evidence_kind"],
    deprecated: false,
  },
  [ErrorCode.COORDINATION_CONFLICT]: {
    code: "MODBIT_COORDINATION_CONFLICT",
    httpStatus: 409,
    retryable: false,
    description: "Unresolved semantic conflict blocks the operation.",
    detailKeys: ["conflict_id", "conflicting_run_id", "scope_kind"],
    deprecated: false,
  },
  [ErrorCode.COORDINATION_UNAVAILABLE]: {
    code: "MODBIT_COORDINATION_UNAVAILABLE",
    httpStatus: 503,
    retryable: true,
    description: "The coordination service is unavailable and the run has registered overlaps (CRC-3).",
    detailKeys: ["run_id"],
    deprecated: false,
  },
  [ErrorCode.DLP_BLOCKED]: {
    code: "MODBIT_DLP_BLOCKED",
    httpStatus: 422,
    retryable: false,
    description: "The outbound payload was blocked by classification or DLP (INV-3).",
    detailKeys: ["policy_decision_id", "classification", "rule_id"],
    deprecated: false,
  },
  [ErrorCode.DLP_UNAVAILABLE]: {
    code: "MODBIT_DLP_UNAVAILABLE",
    httpStatus: 503,
    retryable: true,
    description: "Classification or DLP could not complete; the gateway failed closed.",
    detailKeys: ["reason_class"],
    deprecated: false,
  },
  [ErrorCode.NO_ELIGIBLE_ROUTE]: {
    code: "MODBIT_NO_ELIGIBLE_ROUTE",
    httpStatus: 422,
    retryable: false,
    description: "No model route satisfies the required capabilities within the policy envelope.",
    detailKeys: ["required_capabilities", "policy_decision_id", "rejected_models"],
    deprecated: false,
  },
  [ErrorCode.PROVIDER_UNAVAILABLE]: {
    code: "MODBIT_PROVIDER_UNAVAILABLE",
    httpStatus: 502,
    retryable: true,
    description: "The upstream model provider is unavailable or returned a transport failure.",
    detailKeys: ["provider_id", "upstream_class"],
    deprecated: false,
  },
  [ErrorCode.CANARY_HOLD]: {
    code: "MODBIT_CANARY_HOLD",
    httpStatus: 503,
    retryable: true,
    description: "Route held pending canary passage.",
    detailKeys: ["route_id", "provider_revision", "canary_id"],
    deprecated: false,
  },
  [ErrorCode.CAPABILITY_UNAVAILABLE]: {
    code: "MODBIT_CAPABILITY_UNAVAILABLE",
    httpStatus: 409,
    retryable: false,
    description: "Negotiated capability set does not include the operation.",
    detailKeys: ["capability_id", "operating_mode"],
    deprecated: false,
  },
  [ErrorCode.SANDBOX_UNAVAILABLE]: {
    code: "MODBIT_SANDBOX_UNAVAILABLE",
    httpStatus: 503,
    retryable: false,
    description: "A mandatory sandbox control could not be established; execution failed closed (SBX-6).",
    detailKeys: ["backend", "missing_control"],
    deprecated: false,
  },
  [ErrorCode.LEASE_EXPIRED]: {
    code: "MODBIT_LEASE_EXPIRED",
    httpStatus: 409,
    retryable: false,
    description: "The worker or workspace lease expired before the operation completed.",
    detailKeys: ["lease_id", "expired_at"],
    deprecated: false,
  },
  [ErrorCode.WORKER_UNAVAILABLE]: {
    code: "MODBIT_WORKER_UNAVAILABLE",
    httpStatus: 503,
    retryable: true,
    description: "No eligible worker is available for the environment requirements.",
    detailKeys: ["environment_id", "pool_id"],
    deprecated: false,
  },
  [ErrorCode.NOT_FOUND]: {
    code: "MODBIT_NOT_FOUND",
    httpStatus: 404,
    retryable: false,
    description: "The resource does not exist or is not visible to the actor.",
    detailKeys: ["resource_type"],
    deprecated: false,
  },
  [ErrorCode.CONFLICT]: {
    code: "MODBIT_CONFLICT",
    httpStatus: 409,
    retryable: false,
    description: "The resource changed concurrently; the precondition no longer holds.",
    detailKeys: ["resource_type", "expected_version"],
    deprecated: false,
  },
  [ErrorCode.RATE_LIMITED]: {
    code: "MODBIT_RATE_LIMITED",
    httpStatus: 429,
    retryable: true,
    description: "The actor exceeded a rate limit.",
    detailKeys: ["limit_scope", "retry_after_seconds"],
    deprecated: false,
  },
  [ErrorCode.TIMEOUT]: {
    code: "MODBIT_TIMEOUT",
    httpStatus: 504,
    retryable: true,
    description: "The operation exceeded its deadline.",
    detailKeys: ["operation", "deadline_seconds"],
    deprecated: false,
  },
  [ErrorCode.UNAVAILABLE]: {
    code: "MODBIT_UNAVAILABLE",
    httpStatus: 503,
    retryable: true,
    description: "A dependency is unavailable. The caller may retry within its attempt budget.",
    detailKeys: ["dependency"],
    deprecated: false,
  },
  [ErrorCode.INTERNAL]: {
    code: "MODBIT_INTERNAL",
    httpStatus: 500,
    retryable: false,
    description: "An unexpected internal condition occurred. Details are recorded in the trace only.",
    detailKeys: [],
    deprecated: false,
  },
} as const;
