// Code generated by tools/modbitgen from contracts/events/catalog.yaml. DO NOT EDIT.
//
// Edit the contract and run "make generate". The drift gate in "make check" fails when this file
// is stale.

package event

// CatalogVersion is the version of contracts/events/catalog.yaml this file was generated from.
const CatalogVersion = 1

// Event families.
const (
	// Run lifecycle and phase transitions.
	FamilyRun Family = "run"

	// Step, tool, and model activity inside a run.
	FamilyStep Family = "step"

	// Indexing, snapshots, and retrieval.
	FamilyContext Family = "context"

	// CodeWiki generation and freshness.
	FamilyWiki Family = "wiki"

	// Approval lifecycle.
	FamilyApproval Family = "approval"

	// Worker and environment lifecycle.
	FamilyWorker Family = "worker"

	// Artifact and review outputs.
	FamilyArtifact Family = "artifact"

	// Settings and policy publication.
	FamilySettings Family = "settings"

	// Automation matching and integration effects.
	FamilyAutomation Family = "automation"

	// Operating-mode and instruction resolution.
	FamilyMode Family = "mode"

	// Security Swarm scan, finding, validation, and remediation.
	FamilySecurity Family = "security"

	// Structured Output Contract validation.
	FamilyOutput Family = "output"

	// Governed application deployment.
	FamilyDeployment Family = "deployment"

	// Tiered memory and learning (v5.1).
	FamilyMemory Family = "memory"

	// Provenance taint transitions (v5.1).
	FamilyTaint Family = "taint"

	// Graduated autonomy state changes (v5.1).
	FamilyTrust Family = "trust"

	// Concurrent-run coordination (v5.1).
	FamilyCoordination Family = "coordination"

	// Verification adequacy (v5.1).
	FamilyVerification Family = "verification"

	// Online evaluation and routing (v5.1).
	FamilyEvaluation Family = "evaluation"

	// Evidence export and attachment (v5.1).
	FamilyEvidence Family = "evidence"
)

// Canonical event types. Every authoritative run transition emits one of these (INV-5).
const (
	TypeRunCreated                   Type = "run.created"
	TypeRunClassified                Type = "run.classified"
	TypeRunPhaseChanged              Type = "run.phase.changed"
	TypeRunPaused                    Type = "run.paused"
	TypeRunResumed                   Type = "run.resumed"
	TypeRunBlocked                   Type = "run.blocked"
	TypeRunCompleted                 Type = "run.completed"
	TypeRunFailed                    Type = "run.failed"
	TypeRunCancelled                 Type = "run.cancelled"
	TypeRunReversionCompleted        Type = "run.reversion.completed"
	TypeRunReversionIncomplete       Type = "run.reversion.incomplete"
	TypeRunStepStarted               Type = "run.step.started"
	TypeRunStepProgress              Type = "run.step.progress"
	TypeRunStepCompleted             Type = "run.step.completed"
	TypeRunStepFailed                Type = "run.step.failed"
	TypeToolRequested                Type = "tool.requested"
	TypeToolAuthorized               Type = "tool.authorized"
	TypeToolStarted                  Type = "tool.started"
	TypeToolOutput                   Type = "tool.output"
	TypeToolCompleted                Type = "tool.completed"
	TypeToolFailed                   Type = "tool.failed"
	TypeModelRequested               Type = "model.requested"
	TypeModelRouted                  Type = "model.routed"
	TypeModelStreamDelta             Type = "model.stream.delta"
	TypeModelCompleted               Type = "model.completed"
	TypeModelFailed                  Type = "model.failed"
	TypeModelFailedOver              Type = "model.failed_over"
	TypeContextIndexStarted          Type = "context.index.started"
	TypeContextIndexCompleted        Type = "context.index.completed"
	TypeContextIndexFailed           Type = "context.index.failed"
	TypeContextSnapshotCreated       Type = "context.snapshot.created"
	TypeContextRetrievalCompleted    Type = "context.retrieval.completed"
	TypeWikiGenerationStarted        Type = "wiki.generation.started"
	TypeWikiPageCompleted            Type = "wiki.page.completed"
	TypeWikiGenerationCompleted      Type = "wiki.generation.completed"
	TypeWikiFreshnessChanged         Type = "wiki.freshness.changed"
	TypeApprovalRequested            Type = "approval.requested"
	TypeApprovalExpired              Type = "approval.expired"
	TypeApprovalApproved             Type = "approval.approved"
	TypeApprovalDenied               Type = "approval.denied"
	TypeApprovalRevoked              Type = "approval.revoked"
	TypeWorkerRegistered             Type = "worker.registered"
	TypeWorkerHeartbeat              Type = "worker.heartbeat"
	TypeWorkerLeased                 Type = "worker.leased"
	TypeWorkerDraining               Type = "worker.draining"
	TypeWorkerOffline                Type = "worker.offline"
	TypeEnvironmentBuildStarted      Type = "environment.build.started"
	TypeEnvironmentBuildCompleted    Type = "environment.build.completed"
	TypeEnvironmentBuildFailed       Type = "environment.build.failed"
	TypeArtifactCreated              Type = "artifact.created"
	TypeArtifactVerified             Type = "artifact.verified"
	TypeArtifactRetentionChanged     Type = "artifact.retention.changed"
	TypeReviewFindingCreated         Type = "review.finding.created"
	TypeReviewFindingUpdated         Type = "review.finding.updated"
	TypeReviewCompleted              Type = "review.completed"
	TypeSettingsChanged              Type = "settings.changed"
	TypeSettingsSnapshotCreated      Type = "settings.snapshot.created"
	TypeSettingsMigrationCompleted   Type = "settings.migration.completed"
	TypePolicyBundlePublished        Type = "policy.bundle.published"
	TypePolicyDecisionCreated        Type = "policy.decision.created"
	TypeExternalEventReceived        Type = "external.event.received"
	TypeAutomationMatched            Type = "automation.matched"
	TypeAutomationDeadLettered       Type = "automation.dead_lettered"
	TypeIntegrationEffectRequested   Type = "integration.effect.requested"
	TypeIntegrationEffectCompleted   Type = "integration.effect.completed"
	TypeIntegrationEffectFailed      Type = "integration.effect.failed"
	TypeModeBoundaryChanged          Type = "mode.boundary.changed"
	TypeInstructionManifestCreated   Type = "instruction.manifest.created"
	TypeInstructionConflictDetected  Type = "instruction.conflict.detected"
	TypeRippleAnalysisCompleted      Type = "ripple.analysis.completed"
	TypeRippleSuggestionAccepted     Type = "ripple.suggestion.accepted"
	TypeSecurityScanCreated          Type = "security.scan.created"
	TypeSecurityFindingCreated       Type = "security.finding.created"
	TypeSecurityValidationCompleted  Type = "security.validation.completed"
	TypeSecurityRemediationCompleted Type = "security.remediation.completed"
	TypeOutputValidated              Type = "output.validated"
	TypeOutputValidationFailed       Type = "output.validation.failed"
	TypeDeploymentPlanCreated        Type = "deployment.plan.created"
	TypeDeploymentCompleted          Type = "deployment.completed"
	TypeMemoryCandidateCreated       Type = "memory.candidate.created"
	TypeMemoryCorroborationUpdated   Type = "memory.corroboration.updated"
	TypeMemoryActivated              Type = "memory.activated"
	TypeMemorySuspended              Type = "memory.suspended"
	TypeMemoryRolledBack             Type = "memory.rolled_back"
	TypeMemoryPromotionRequested     Type = "memory.promotion.requested"
	TypeRetrievalAdaptationActivated Type = "retrieval.adaptation.activated"
	TypeTaintClassEntered            Type = "taint.class.entered"
	TypeTaintEscalationApplied       Type = "taint.escalation.applied"
	TypeTaintDeclassified            Type = "taint.declassified"
	TypeTrustAccrued                 Type = "trust.accrued"
	TypeTrustDowngraded              Type = "trust.downgraded"
	TypeTrustReversed                Type = "trust.reversed"
	TypeCoordinationScopeRegistered  Type = "coordination.scope.registered"
	TypeCoordinationOverlapDetected  Type = "coordination.overlap.detected"
	TypeCoordinationLockAcquired     Type = "coordination.lock.acquired"
	TypeCoordinationLockReleased     Type = "coordination.lock.released"
	TypeCoordinationConflictDetected Type = "coordination.conflict.detected"
	TypeCoordinationRebaseReverified Type = "coordination.rebase.reverified"
	TypeVerificationAdequacyComputed Type = "verification.adequacy.computed"
	TypeVerificationAdequacyBlocked  Type = "verification.adequacy.blocked"
	TypeEvaluationRevisionDetected   Type = "evaluation.revision.detected"
	TypeEvaluationCanaryStarted      Type = "evaluation.canary.started"
	TypeEvaluationCanaryCompleted    Type = "evaluation.canary.completed"
	TypeEvaluationCanaryFailed       Type = "evaluation.canary.failed"
	TypeEvaluationShadowCompleted    Type = "evaluation.shadow.completed"
	TypeEvaluationGateEvaluated      Type = "evaluation.gate.evaluated"
	TypeEvaluationDriftAlerted       Type = "evaluation.drift.alerted"
	TypeRoutingCascadeEscalated      Type = "routing.cascade.escalated"
	TypeEvidenceExportRequested      Type = "evidence.export.requested"
	TypeEvidenceExportCompleted      Type = "evidence.export.completed"
)

// specs is the generated catalog consulted by New and Validate.
var specs = map[Type]Spec{
	TypeRunCreated: {
		Type:    "run.created",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeRunClassified: {
		Type:    "run.classified",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeRunPhaseChanged: {
		Type:    "run.phase.changed",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeRunPaused: {
		Type:    "run.paused",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeRunResumed: {
		Type:    "run.resumed",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeRunBlocked: {
		Type:    "run.blocked",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeRunCompleted: {
		Type:    "run.completed",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeRunFailed: {
		Type:    "run.failed",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeRunCancelled: {
		Type:    "run.cancelled",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeRunReversionCompleted: {
		Type:    "run.reversion.completed",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeRunReversionIncomplete: {
		Type:    "run.reversion.incomplete",
		Version: 1,
		Family:  "run",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeRunStepStarted: {
		Type:    "run.step.started",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeRunStepProgress: {
		Type:    "run.step.progress",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeRunStepCompleted: {
		Type:    "run.step.completed",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeRunStepFailed: {
		Type:    "run.step.failed",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeToolRequested: {
		Type:    "tool.requested",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeToolAuthorized: {
		Type:    "tool.authorized",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeToolStarted: {
		Type:    "tool.started",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeToolOutput: {
		Type:    "tool.output",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeToolCompleted: {
		Type:    "tool.completed",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeToolFailed: {
		Type:    "tool.failed",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeModelRequested: {
		Type:    "model.requested",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeModelRouted: {
		Type:    "model.routed",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeModelStreamDelta: {
		Type:    "model.stream.delta",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeModelCompleted: {
		Type:    "model.completed",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeModelFailed: {
		Type:    "model.failed",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeModelFailedOver: {
		Type:    "model.failed_over",
		Version: 1,
		Family:  "step",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeContextIndexStarted: {
		Type:    "context.index.started",
		Version: 1,
		Family:  "context",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeContextIndexCompleted: {
		Type:    "context.index.completed",
		Version: 1,
		Family:  "context",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeContextIndexFailed: {
		Type:    "context.index.failed",
		Version: 1,
		Family:  "context",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeContextSnapshotCreated: {
		Type:    "context.snapshot.created",
		Version: 1,
		Family:  "context",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeContextRetrievalCompleted: {
		Type:    "context.retrieval.completed",
		Version: 1,
		Family:  "context",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeWikiGenerationStarted: {
		Type:    "wiki.generation.started",
		Version: 1,
		Family:  "wiki",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeWikiPageCompleted: {
		Type:    "wiki.page.completed",
		Version: 1,
		Family:  "wiki",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeWikiGenerationCompleted: {
		Type:    "wiki.generation.completed",
		Version: 1,
		Family:  "wiki",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeWikiFreshnessChanged: {
		Type:    "wiki.freshness.changed",
		Version: 1,
		Family:  "wiki",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeApprovalRequested: {
		Type:    "approval.requested",
		Version: 1,
		Family:  "approval",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeApprovalExpired: {
		Type:    "approval.expired",
		Version: 1,
		Family:  "approval",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeApprovalApproved: {
		Type:    "approval.approved",
		Version: 1,
		Family:  "approval",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeApprovalDenied: {
		Type:    "approval.denied",
		Version: 1,
		Family:  "approval",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeApprovalRevoked: {
		Type:    "approval.revoked",
		Version: 1,
		Family:  "approval",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeWorkerRegistered: {
		Type:    "worker.registered",
		Version: 1,
		Family:  "worker",
		Scope:   ScopeWorker,
		Audit:   true,
	},
	TypeWorkerHeartbeat: {
		Type:    "worker.heartbeat",
		Version: 1,
		Family:  "worker",
		Scope:   ScopeWorker,
		Audit:   false,
	},
	TypeWorkerLeased: {
		Type:    "worker.leased",
		Version: 1,
		Family:  "worker",
		Scope:   ScopeWorker,
		Audit:   true,
	},
	TypeWorkerDraining: {
		Type:    "worker.draining",
		Version: 1,
		Family:  "worker",
		Scope:   ScopeWorker,
		Audit:   false,
	},
	TypeWorkerOffline: {
		Type:    "worker.offline",
		Version: 1,
		Family:  "worker",
		Scope:   ScopeWorker,
		Audit:   true,
	},
	TypeEnvironmentBuildStarted: {
		Type:    "environment.build.started",
		Version: 1,
		Family:  "worker",
		Scope:   ScopeOrganization,
		Audit:   false,
	},
	TypeEnvironmentBuildCompleted: {
		Type:    "environment.build.completed",
		Version: 1,
		Family:  "worker",
		Scope:   ScopeOrganization,
		Audit:   false,
	},
	TypeEnvironmentBuildFailed: {
		Type:    "environment.build.failed",
		Version: 1,
		Family:  "worker",
		Scope:   ScopeOrganization,
		Audit:   false,
	},
	TypeArtifactCreated: {
		Type:    "artifact.created",
		Version: 1,
		Family:  "artifact",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeArtifactVerified: {
		Type:    "artifact.verified",
		Version: 1,
		Family:  "artifact",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeArtifactRetentionChanged: {
		Type:    "artifact.retention.changed",
		Version: 1,
		Family:  "artifact",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeReviewFindingCreated: {
		Type:    "review.finding.created",
		Version: 1,
		Family:  "artifact",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeReviewFindingUpdated: {
		Type:    "review.finding.updated",
		Version: 1,
		Family:  "artifact",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeReviewCompleted: {
		Type:    "review.completed",
		Version: 1,
		Family:  "artifact",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeSettingsChanged: {
		Type:    "settings.changed",
		Version: 1,
		Family:  "settings",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeSettingsSnapshotCreated: {
		Type:    "settings.snapshot.created",
		Version: 1,
		Family:  "settings",
		Scope:   ScopeOrganization,
		Audit:   false,
	},
	TypeSettingsMigrationCompleted: {
		Type:    "settings.migration.completed",
		Version: 1,
		Family:  "settings",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypePolicyBundlePublished: {
		Type:    "policy.bundle.published",
		Version: 1,
		Family:  "settings",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypePolicyDecisionCreated: {
		Type:    "policy.decision.created",
		Version: 1,
		Family:  "settings",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeExternalEventReceived: {
		Type:    "external.event.received",
		Version: 1,
		Family:  "automation",
		Scope:   ScopeOrganization,
		Audit:   false,
	},
	TypeAutomationMatched: {
		Type:    "automation.matched",
		Version: 1,
		Family:  "automation",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeAutomationDeadLettered: {
		Type:    "automation.dead_lettered",
		Version: 1,
		Family:  "automation",
		Scope:   ScopeSpace,
		Audit:   true,
	},
	TypeIntegrationEffectRequested: {
		Type:    "integration.effect.requested",
		Version: 1,
		Family:  "automation",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeIntegrationEffectCompleted: {
		Type:    "integration.effect.completed",
		Version: 1,
		Family:  "automation",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeIntegrationEffectFailed: {
		Type:    "integration.effect.failed",
		Version: 1,
		Family:  "automation",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeModeBoundaryChanged: {
		Type:    "mode.boundary.changed",
		Version: 1,
		Family:  "mode",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeInstructionManifestCreated: {
		Type:    "instruction.manifest.created",
		Version: 1,
		Family:  "mode",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeInstructionConflictDetected: {
		Type:    "instruction.conflict.detected",
		Version: 1,
		Family:  "mode",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeRippleAnalysisCompleted: {
		Type:    "ripple.analysis.completed",
		Version: 1,
		Family:  "context",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeRippleSuggestionAccepted: {
		Type:    "ripple.suggestion.accepted",
		Version: 1,
		Family:  "context",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeSecurityScanCreated: {
		Type:    "security.scan.created",
		Version: 1,
		Family:  "security",
		Scope:   ScopeSpace,
		Audit:   true,
	},
	TypeSecurityFindingCreated: {
		Type:    "security.finding.created",
		Version: 1,
		Family:  "security",
		Scope:   ScopeSpace,
		Audit:   true,
	},
	TypeSecurityValidationCompleted: {
		Type:    "security.validation.completed",
		Version: 1,
		Family:  "security",
		Scope:   ScopeSpace,
		Audit:   true,
	},
	TypeSecurityRemediationCompleted: {
		Type:    "security.remediation.completed",
		Version: 1,
		Family:  "security",
		Scope:   ScopeSpace,
		Audit:   true,
	},
	TypeOutputValidated: {
		Type:    "output.validated",
		Version: 1,
		Family:  "output",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeOutputValidationFailed: {
		Type:    "output.validation.failed",
		Version: 1,
		Family:  "output",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeDeploymentPlanCreated: {
		Type:    "deployment.plan.created",
		Version: 1,
		Family:  "deployment",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeDeploymentCompleted: {
		Type:    "deployment.completed",
		Version: 1,
		Family:  "deployment",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeMemoryCandidateCreated: {
		Type:    "memory.candidate.created",
		Version: 1,
		Family:  "memory",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeMemoryCorroborationUpdated: {
		Type:    "memory.corroboration.updated",
		Version: 1,
		Family:  "memory",
		Scope:   ScopeSpace,
		Audit:   false,
	},
	TypeMemoryActivated: {
		Type:    "memory.activated",
		Version: 1,
		Family:  "memory",
		Scope:   ScopeSpace,
		Audit:   true,
	},
	TypeMemorySuspended: {
		Type:    "memory.suspended",
		Version: 1,
		Family:  "memory",
		Scope:   ScopeSpace,
		Audit:   true,
	},
	TypeMemoryRolledBack: {
		Type:    "memory.rolled_back",
		Version: 1,
		Family:  "memory",
		Scope:   ScopeSpace,
		Audit:   true,
	},
	TypeMemoryPromotionRequested: {
		Type:    "memory.promotion.requested",
		Version: 1,
		Family:  "memory",
		Scope:   ScopeSpace,
		Audit:   true,
	},
	TypeRetrievalAdaptationActivated: {
		Type:    "retrieval.adaptation.activated",
		Version: 1,
		Family:  "memory",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeTaintClassEntered: {
		Type:    "taint.class.entered",
		Version: 1,
		Family:  "taint",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeTaintEscalationApplied: {
		Type:    "taint.escalation.applied",
		Version: 1,
		Family:  "taint",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeTaintDeclassified: {
		Type:    "taint.declassified",
		Version: 1,
		Family:  "taint",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeTrustAccrued: {
		Type:    "trust.accrued",
		Version: 1,
		Family:  "trust",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeTrustDowngraded: {
		Type:    "trust.downgraded",
		Version: 1,
		Family:  "trust",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeTrustReversed: {
		Type:    "trust.reversed",
		Version: 1,
		Family:  "trust",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeCoordinationScopeRegistered: {
		Type:    "coordination.scope.registered",
		Version: 1,
		Family:  "coordination",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeCoordinationOverlapDetected: {
		Type:    "coordination.overlap.detected",
		Version: 1,
		Family:  "coordination",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeCoordinationLockAcquired: {
		Type:    "coordination.lock.acquired",
		Version: 1,
		Family:  "coordination",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeCoordinationLockReleased: {
		Type:    "coordination.lock.released",
		Version: 1,
		Family:  "coordination",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeCoordinationConflictDetected: {
		Type:    "coordination.conflict.detected",
		Version: 1,
		Family:  "coordination",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeCoordinationRebaseReverified: {
		Type:    "coordination.rebase.reverified",
		Version: 1,
		Family:  "coordination",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeVerificationAdequacyComputed: {
		Type:    "verification.adequacy.computed",
		Version: 1,
		Family:  "verification",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeVerificationAdequacyBlocked: {
		Type:    "verification.adequacy.blocked",
		Version: 1,
		Family:  "verification",
		Scope:   ScopeRun,
		Audit:   true,
	},
	TypeEvaluationRevisionDetected: {
		Type:    "evaluation.revision.detected",
		Version: 1,
		Family:  "evaluation",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeEvaluationCanaryStarted: {
		Type:    "evaluation.canary.started",
		Version: 1,
		Family:  "evaluation",
		Scope:   ScopeOrganization,
		Audit:   false,
	},
	TypeEvaluationCanaryCompleted: {
		Type:    "evaluation.canary.completed",
		Version: 1,
		Family:  "evaluation",
		Scope:   ScopeOrganization,
		Audit:   false,
	},
	TypeEvaluationCanaryFailed: {
		Type:    "evaluation.canary.failed",
		Version: 1,
		Family:  "evaluation",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeEvaluationShadowCompleted: {
		Type:    "evaluation.shadow.completed",
		Version: 1,
		Family:  "evaluation",
		Scope:   ScopeOrganization,
		Audit:   false,
	},
	TypeEvaluationGateEvaluated: {
		Type:    "evaluation.gate.evaluated",
		Version: 1,
		Family:  "evaluation",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeEvaluationDriftAlerted: {
		Type:    "evaluation.drift.alerted",
		Version: 1,
		Family:  "evaluation",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeRoutingCascadeEscalated: {
		Type:    "routing.cascade.escalated",
		Version: 1,
		Family:  "evaluation",
		Scope:   ScopeRun,
		Audit:   false,
	},
	TypeEvidenceExportRequested: {
		Type:    "evidence.export.requested",
		Version: 1,
		Family:  "evidence",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
	TypeEvidenceExportCompleted: {
		Type:    "evidence.export.completed",
		Version: 1,
		Family:  "evidence",
		Scope:   ScopeOrganization,
		Audit:   true,
	},
}
