// Code generated by tools/modbitgen from contracts/errors/catalog.yaml. DO NOT EDIT.
//
// Edit the contract and run "make generate". The drift gate in "make check" fails when this file
// is stale.

package modberr

// CatalogVersion is the version of contracts/errors/catalog.yaml this file was generated from.
const CatalogVersion = 1

// Stable Modbit error codes. Codes are append-only and never reused (R-ERR-01).
const (
	// The request was malformed or violated a field constraint.
	CodeInvalidArgument Code = "MODBIT_INVALID_ARGUMENT"

	// The requested API, event, schema, or worker protocol version is not supported.
	CodeUnsupportedVersion Code = "MODBIT_UNSUPPORTED_VERSION"

	// A structured artifact failed validation against its Structured Output Contract.
	CodeContractValidationFailed Code = "MODBIT_CONTRACT_VALIDATION_FAILED"

	// No valid credential was presented.
	CodeUnauthenticated Code = "MODBIT_UNAUTHENTICATED"

	// The authenticated actor lacks permission for this operation.
	CodePermissionDenied Code = "MODBIT_PERMISSION_DENIED"

	// The referenced resource belongs to a different organization or Space.
	CodeTenantMismatch Code = "MODBIT_TENANT_MISMATCH"

	// Operation denied by policy.
	CodePolicyDenied Code = "MODBIT_POLICY_DENIED"

	// The operation requires human approval before it may proceed.
	CodeApprovalRequired Code = "MODBIT_APPROVAL_REQUIRED"

	// A required approval was denied or revoked.
	CodeApprovalDenied Code = "MODBIT_APPROVAL_DENIED"

	// The operation changed after approval; the prior approval no longer binds (SFX-4).
	CodeApprovalInvalidated Code = "MODBIT_APPROVAL_INVALIDATED"

	// Operation requires elevated approval due to taint state.
	CodeTaintEscalationRequired Code = "MODBIT_TAINT_ESCALATION_REQUIRED"

	// The settings key is not present in the Settings Registry.
	CodeSettingUnknown Code = "MODBIT_SETTING_UNKNOWN"

	// The settings value failed type, enum, or range validation.
	CodeSettingInvalid Code = "MODBIT_SETTING_INVALID"

	// A higher settings scope locks this key; lower scopes cannot change it.
	CodeSettingLocked Code = "MODBIT_SETTING_LOCKED"

	// The value falls outside the compiled policy envelope for this key.
	CodeSettingPolicyViolation Code = "MODBIT_SETTING_POLICY_VIOLATION"

	// The run does not exist or is not visible to the actor.
	CodeRunNotFound Code = "MODBIT_RUN_NOT_FOUND"

	// The command is not valid for the run's current phase.
	CodeRunStateInvalid Code = "MODBIT_RUN_STATE_INVALID"

	// Another transition lease is active for this run (R-EVT-06).
	CodeTransitionLeaseHeld Code = "MODBIT_TRANSITION_LEASE_HELD"

	// The event sequence allocated for this run is no longer current.
	CodeSequenceConflict Code = "MODBIT_SEQUENCE_CONFLICT"

	// The idempotency key was reused with a different request body.
	CodeIdempotencyConflict Code = "MODBIT_IDEMPOTENCY_CONFLICT"

	// The run, Space, or organization budget is exhausted.
	CodeBudgetExhausted Code = "MODBIT_BUDGET_EXHAUSTED"

	// The operation was cancelled by an actor or a parent run.
	CodeCancelled Code = "MODBIT_CANCELLED"

	// The operation was superseded by a later instruction or run.
	CodeSuperseded Code = "MODBIT_SUPERSEDED"

	// The repository revision or unsaved overlay no longer matches the run's snapshot.
	CodeSnapshotDiverged Code = "MODBIT_SNAPSHOT_DIVERGED"

	// An external effect may have occurred but its receipt is missing; reconcile before retrying.
	CodeEffectReconciliationRequired Code = "MODBIT_EFFECT_RECONCILIATION_REQUIRED"

	// One or more retrieval channels are unavailable; the response declares the degradation.
	CodeContextDegraded Code = "MODBIT_CONTEXT_DEGRADED"

	// Safe restoration could not be proven; the run entered reversion_incomplete (RCV-7).
	CodeReversionIncomplete Code = "MODBIT_REVERSION_INCOMPLETE"

	// Evidence below configured adequacy threshold.
	CodeAdequacyThresholdFailed Code = "MODBIT_ADEQUACY_THRESHOLD_FAILED"

	// Completion was claimed without the evidence its completion contract requires.
	CodeEvidenceMissing Code = "MODBIT_EVIDENCE_MISSING"

	// Unresolved semantic conflict blocks the operation.
	CodeCoordinationConflict Code = "MODBIT_COORDINATION_CONFLICT"

	// The coordination service is unavailable and the run has registered overlaps (CRC-3).
	CodeCoordinationUnavailable Code = "MODBIT_COORDINATION_UNAVAILABLE"

	// The outbound payload was blocked by classification or DLP (INV-3).
	CodeDLPBlocked Code = "MODBIT_DLP_BLOCKED"

	// Classification or DLP could not complete; the gateway failed closed.
	CodeDLPUnavailable Code = "MODBIT_DLP_UNAVAILABLE"

	// No model route satisfies the required capabilities within the policy envelope.
	CodeNoEligibleRoute Code = "MODBIT_NO_ELIGIBLE_ROUTE"

	// The upstream model provider is unavailable or returned a transport failure.
	CodeProviderUnavailable Code = "MODBIT_PROVIDER_UNAVAILABLE"

	// Route held pending canary passage.
	CodeCanaryHold Code = "MODBIT_CANARY_HOLD"

	// Negotiated capability set does not include the operation.
	CodeCapabilityUnavailable Code = "MODBIT_CAPABILITY_UNAVAILABLE"

	// A mandatory sandbox control could not be established; execution failed closed (SBX-6).
	CodeSandboxUnavailable Code = "MODBIT_SANDBOX_UNAVAILABLE"

	// The worker or workspace lease expired before the operation completed.
	CodeLeaseExpired Code = "MODBIT_LEASE_EXPIRED"

	// No eligible worker is available for the environment requirements.
	CodeWorkerUnavailable Code = "MODBIT_WORKER_UNAVAILABLE"

	// The resource does not exist or is not visible to the actor.
	CodeNotFound Code = "MODBIT_NOT_FOUND"

	// The resource changed concurrently; the precondition no longer holds.
	CodeConflict Code = "MODBIT_CONFLICT"

	// The actor exceeded a rate limit.
	CodeRateLimited Code = "MODBIT_RATE_LIMITED"

	// The operation exceeded its deadline.
	CodeTimeout Code = "MODBIT_TIMEOUT"

	// A dependency is unavailable. The caller may retry within its attempt budget.
	CodeUnavailable Code = "MODBIT_UNAVAILABLE"

	// An unexpected internal condition occurred. Details are recorded in the trace only.
	CodeInternal Code = "MODBIT_INTERNAL"
)

// specs is the generated code registry consulted by New, Wrap, and WithDetail.
var specs = map[Code]Spec{
	CodeInvalidArgument: {
		Code:        "MODBIT_INVALID_ARGUMENT",
		HTTPStatus:  400,
		Retryable:   false,
		Description: "The request was malformed or violated a field constraint.",
		DetailKeys:  []string{"field", "constraint"},
		Deprecated:  false,
	},
	CodeUnsupportedVersion: {
		Code:        "MODBIT_UNSUPPORTED_VERSION",
		HTTPStatus:  400,
		Retryable:   false,
		Description: "The requested API, event, schema, or worker protocol version is not supported.",
		DetailKeys:  []string{"requested_version", "supported_versions"},
		Deprecated:  false,
	},
	CodeContractValidationFailed: {
		Code:        "MODBIT_CONTRACT_VALIDATION_FAILED",
		HTTPStatus:  422,
		Retryable:   false,
		Description: "A structured artifact failed validation against its Structured Output Contract.",
		DetailKeys:  []string{"schema_id", "schema_version", "artifact_id", "violation_count"},
		Deprecated:  false,
	},
	CodeUnauthenticated: {
		Code:        "MODBIT_UNAUTHENTICATED",
		HTTPStatus:  401,
		Retryable:   false,
		Description: "No valid credential was presented.",
		DetailKeys:  []string{"scheme"},
		Deprecated:  false,
	},
	CodePermissionDenied: {
		Code:        "MODBIT_PERMISSION_DENIED",
		HTTPStatus:  403,
		Retryable:   false,
		Description: "The authenticated actor lacks permission for this operation.",
		DetailKeys:  []string{"required_role", "resource_type"},
		Deprecated:  false,
	},
	CodeTenantMismatch: {
		Code:        "MODBIT_TENANT_MISMATCH",
		HTTPStatus:  403,
		Retryable:   false,
		Description: "The referenced resource belongs to a different organization or Space.",
		DetailKeys:  []string{"resource_type"},
		Deprecated:  false,
	},
	CodePolicyDenied: {
		Code:        "MODBIT_POLICY_DENIED",
		HTTPStatus:  403,
		Retryable:   false,
		Description: "Operation denied by policy.",
		DetailKeys:  []string{"policy_decision_id", "rule_id", "side_effect_class"},
		Deprecated:  false,
	},
	CodeApprovalRequired: {
		Code:        "MODBIT_APPROVAL_REQUIRED",
		HTTPStatus:  428,
		Retryable:   false,
		Description: "The operation requires human approval before it may proceed.",
		DetailKeys:  []string{"policy_decision_id", "approval_id", "approval_class", "side_effect_class"},
		Deprecated:  false,
	},
	CodeApprovalDenied: {
		Code:        "MODBIT_APPROVAL_DENIED",
		HTTPStatus:  403,
		Retryable:   false,
		Description: "A required approval was denied or revoked.",
		DetailKeys:  []string{"policy_decision_id", "approval_id"},
		Deprecated:  false,
	},
	CodeApprovalInvalidated: {
		Code:        "MODBIT_APPROVAL_INVALIDATED",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "The operation changed after approval; the prior approval no longer binds (SFX-4).",
		DetailKeys:  []string{"approval_id", "expected_operation_hash", "actual_operation_hash", "fence_epoch", "approval_scope"},
		Deprecated:  false,
	},
	CodeTaintEscalationRequired: {
		Code:        "MODBIT_TAINT_ESCALATION_REQUIRED",
		HTTPStatus:  428,
		Retryable:   false,
		Description: "Operation requires elevated approval due to taint state.",
		DetailKeys:  []string{"policy_decision_id", "approval_class", "escalated_from", "taint_classes", "side_effect_class"},
		Deprecated:  false,
	},
	CodeSettingUnknown: {
		Code:        "MODBIT_SETTING_UNKNOWN",
		HTTPStatus:  400,
		Retryable:   false,
		Description: "The settings key is not present in the Settings Registry.",
		DetailKeys:  []string{"setting_key"},
		Deprecated:  false,
	},
	CodeSettingInvalid: {
		Code:        "MODBIT_SETTING_INVALID",
		HTTPStatus:  400,
		Retryable:   false,
		Description: "The settings value failed type, enum, or range validation.",
		DetailKeys:  []string{"setting_key", "setting_scope", "expected_type"},
		Deprecated:  false,
	},
	CodeSettingLocked: {
		Code:        "MODBIT_SETTING_LOCKED",
		HTTPStatus:  403,
		Retryable:   false,
		Description: "A higher settings scope locks this key; lower scopes cannot change it.",
		DetailKeys:  []string{"setting_key", "locked_by_scope"},
		Deprecated:  false,
	},
	CodeSettingPolicyViolation: {
		Code:        "MODBIT_SETTING_POLICY_VIOLATION",
		HTTPStatus:  403,
		Retryable:   false,
		Description: "The value falls outside the compiled policy envelope for this key.",
		DetailKeys:  []string{"setting_key", "setting_scope", "envelope_source_scope"},
		Deprecated:  false,
	},
	CodeRunNotFound: {
		Code:        "MODBIT_RUN_NOT_FOUND",
		HTTPStatus:  404,
		Retryable:   false,
		Description: "The run does not exist or is not visible to the actor.",
		DetailKeys:  []string{"run_id"},
		Deprecated:  false,
	},
	CodeRunStateInvalid: {
		Code:        "MODBIT_RUN_STATE_INVALID",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "The command is not valid for the run's current phase.",
		DetailKeys:  []string{"run_id", "current_phase", "requested_command"},
		Deprecated:  false,
	},
	CodeTransitionLeaseHeld: {
		Code:        "MODBIT_TRANSITION_LEASE_HELD",
		HTTPStatus:  409,
		Retryable:   true,
		Description: "Another transition lease is active for this run (R-EVT-06).",
		DetailKeys:  []string{"run_id", "lease_expires_at"},
		Deprecated:  false,
	},
	CodeSequenceConflict: {
		Code:        "MODBIT_SEQUENCE_CONFLICT",
		HTTPStatus:  409,
		Retryable:   true,
		Description: "The event sequence allocated for this run is no longer current.",
		DetailKeys:  []string{"run_id", "expected_sequence", "actual_sequence"},
		Deprecated:  false,
	},
	CodeIdempotencyConflict: {
		Code:        "MODBIT_IDEMPOTENCY_CONFLICT",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "The idempotency key was reused with a different request body.",
		DetailKeys:  []string{"idempotency_key"},
		Deprecated:  false,
	},
	CodeBudgetExhausted: {
		Code:        "MODBIT_BUDGET_EXHAUSTED",
		HTTPStatus:  402,
		Retryable:   false,
		Description: "The run, Space, or organization budget is exhausted.",
		DetailKeys:  []string{"budget_id", "budget_scope"},
		Deprecated:  false,
	},
	CodeCancelled: {
		Code:        "MODBIT_CANCELLED",
		HTTPStatus:  499,
		Retryable:   false,
		Description: "The operation was cancelled by an actor or a parent run.",
		DetailKeys:  []string{"run_id", "cancelled_by"},
		Deprecated:  false,
	},
	CodeSuperseded: {
		Code:        "MODBIT_SUPERSEDED",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "The operation was superseded by a later instruction or run.",
		DetailKeys:  []string{"run_id", "superseded_by"},
		Deprecated:  false,
	},
	CodeSnapshotDiverged: {
		Code:        "MODBIT_SNAPSHOT_DIVERGED",
		HTTPStatus:  412,
		Retryable:   false,
		Description: "The repository revision or unsaved overlay no longer matches the run's snapshot.",
		DetailKeys:  []string{"run_id", "expected_revision", "actual_revision", "resource_type"},
		Deprecated:  false,
	},
	CodeEffectReconciliationRequired: {
		Code:        "MODBIT_EFFECT_RECONCILIATION_REQUIRED",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "An external effect may have occurred but its receipt is missing; reconcile before retrying.",
		DetailKeys:  []string{"run_id", "step_id", "effect_key", "integration_id"},
		Deprecated:  false,
	},
	CodeContextDegraded: {
		Code:        "MODBIT_CONTEXT_DEGRADED",
		HTTPStatus:  206,
		Retryable:   true,
		Description: "One or more retrieval channels are unavailable; the response declares the degradation.",
		DetailKeys:  []string{"degraded_channels", "healthy_channels", "space_id"},
		Deprecated:  false,
	},
	CodeReversionIncomplete: {
		Code:        "MODBIT_REVERSION_INCOMPLETE",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "Safe restoration could not be proven; the run entered reversion_incomplete (RCV-7).",
		DetailKeys:  []string{"run_id", "checkpoint_id", "unresolved_count"},
		Deprecated:  false,
	},
	CodeAdequacyThresholdFailed: {
		Code:        "MODBIT_ADEQUACY_THRESHOLD_FAILED",
		HTTPStatus:  422,
		Retryable:   false,
		Description: "Evidence below configured adequacy threshold.",
		DetailKeys:  []string{"run_id", "adequacy_method", "score", "threshold"},
		Deprecated:  false,
	},
	CodeEvidenceMissing: {
		Code:        "MODBIT_EVIDENCE_MISSING",
		HTTPStatus:  422,
		Retryable:   false,
		Description: "Completion was claimed without the evidence its completion contract requires.",
		DetailKeys:  []string{"run_id", "contract_id", "missing_evidence_kind"},
		Deprecated:  false,
	},
	CodeCoordinationConflict: {
		Code:        "MODBIT_COORDINATION_CONFLICT",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "Unresolved semantic conflict blocks the operation.",
		DetailKeys:  []string{"conflict_id", "conflicting_run_id", "scope_kind"},
		Deprecated:  false,
	},
	CodeCoordinationUnavailable: {
		Code:        "MODBIT_COORDINATION_UNAVAILABLE",
		HTTPStatus:  503,
		Retryable:   true,
		Description: "The coordination service is unavailable and the run has registered overlaps (CRC-3).",
		DetailKeys:  []string{"run_id"},
		Deprecated:  false,
	},
	CodeDLPBlocked: {
		Code:        "MODBIT_DLP_BLOCKED",
		HTTPStatus:  422,
		Retryable:   false,
		Description: "The outbound payload was blocked by classification or DLP (INV-3).",
		DetailKeys:  []string{"policy_decision_id", "classification", "rule_id"},
		Deprecated:  false,
	},
	CodeDLPUnavailable: {
		Code:        "MODBIT_DLP_UNAVAILABLE",
		HTTPStatus:  503,
		Retryable:   true,
		Description: "Classification or DLP could not complete; the gateway failed closed.",
		DetailKeys:  []string{"reason_class"},
		Deprecated:  false,
	},
	CodeNoEligibleRoute: {
		Code:        "MODBIT_NO_ELIGIBLE_ROUTE",
		HTTPStatus:  422,
		Retryable:   false,
		Description: "No model route satisfies the required capabilities within the policy envelope.",
		DetailKeys:  []string{"required_capabilities", "policy_decision_id", "rejected_models"},
		Deprecated:  false,
	},
	CodeProviderUnavailable: {
		Code:        "MODBIT_PROVIDER_UNAVAILABLE",
		HTTPStatus:  502,
		Retryable:   true,
		Description: "The upstream model provider is unavailable or returned a transport failure.",
		DetailKeys:  []string{"provider_id", "upstream_class"},
		Deprecated:  false,
	},
	CodeCanaryHold: {
		Code:        "MODBIT_CANARY_HOLD",
		HTTPStatus:  503,
		Retryable:   true,
		Description: "Route held pending canary passage.",
		DetailKeys:  []string{"route_id", "provider_revision", "canary_id"},
		Deprecated:  false,
	},
	CodeCapabilityUnavailable: {
		Code:        "MODBIT_CAPABILITY_UNAVAILABLE",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "Negotiated capability set does not include the operation.",
		DetailKeys:  []string{"capability_id", "operating_mode"},
		Deprecated:  false,
	},
	CodeSandboxUnavailable: {
		Code:        "MODBIT_SANDBOX_UNAVAILABLE",
		HTTPStatus:  503,
		Retryable:   false,
		Description: "A mandatory sandbox control could not be established; execution failed closed (SBX-6).",
		DetailKeys:  []string{"backend", "missing_control"},
		Deprecated:  false,
	},
	CodeLeaseExpired: {
		Code:        "MODBIT_LEASE_EXPIRED",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "The worker or workspace lease expired before the operation completed.",
		DetailKeys:  []string{"lease_id", "expired_at"},
		Deprecated:  false,
	},
	CodeWorkerUnavailable: {
		Code:        "MODBIT_WORKER_UNAVAILABLE",
		HTTPStatus:  503,
		Retryable:   true,
		Description: "No eligible worker is available for the environment requirements.",
		DetailKeys:  []string{"environment_id", "pool_id"},
		Deprecated:  false,
	},
	CodeNotFound: {
		Code:        "MODBIT_NOT_FOUND",
		HTTPStatus:  404,
		Retryable:   false,
		Description: "The resource does not exist or is not visible to the actor.",
		DetailKeys:  []string{"resource_type"},
		Deprecated:  false,
	},
	CodeConflict: {
		Code:        "MODBIT_CONFLICT",
		HTTPStatus:  409,
		Retryable:   false,
		Description: "The resource changed concurrently; the precondition no longer holds.",
		DetailKeys:  []string{"resource_type", "expected_version"},
		Deprecated:  false,
	},
	CodeRateLimited: {
		Code:        "MODBIT_RATE_LIMITED",
		HTTPStatus:  429,
		Retryable:   true,
		Description: "The actor exceeded a rate limit.",
		DetailKeys:  []string{"limit_scope", "retry_after_seconds"},
		Deprecated:  false,
	},
	CodeTimeout: {
		Code:        "MODBIT_TIMEOUT",
		HTTPStatus:  504,
		Retryable:   true,
		Description: "The operation exceeded its deadline.",
		DetailKeys:  []string{"operation", "deadline_seconds"},
		Deprecated:  false,
	},
	CodeUnavailable: {
		Code:        "MODBIT_UNAVAILABLE",
		HTTPStatus:  503,
		Retryable:   true,
		Description: "A dependency is unavailable. The caller may retry within its attempt budget.",
		DetailKeys:  []string{"dependency"},
		Deprecated:  false,
	},
	CodeInternal: {
		Code:        "MODBIT_INTERNAL",
		HTTPStatus:  500,
		Retryable:   false,
		Description: "An unexpected internal condition occurred. Details are recorded in the trace only.",
		DetailKeys:  nil,
		Deprecated:  false,
	},
}
