package index

import (
	"bytes"
	"path"
	"strings"
	"unicode/utf8"

	"github.com/modbit/modbit/pkg/modberr"
	"github.com/modbit/modbit/pkg/settings"
	"github.com/modbit/modbit/pkg/taint"
)

// Disposition is what may be done with a file.
type Disposition string

const (
	// DispositionIndex permits lexical, semantic, and symbol indexing.
	DispositionIndex Disposition = "index"
	// DispositionReference records the path as citable without indexing its contents. A large
	// fixture or a binary asset still exists and may be named in a citation; parsing or embedding it
	// would waste budget and produce noise.
	DispositionReference Disposition = "reference"
	// DispositionExclude removes the file from retrieval entirely. It is not citable and its path
	// is not recorded, because a path is itself information.
	DispositionExclude Disposition = "exclude"
)

// Reason codes explain a decision. They are stable strings shown in the context health view and in
// the retrieval debug surface, so a user can see why a file they expected is missing.
const (
	ReasonIncluded          = "included"
	ReasonProtectedPath     = "protected_path"
	ReasonIgnoreFile        = "ignore_file"
	ReasonSettingsExclusion = "settings_exclusion"
	ReasonTooLarge          = "too_large"
	ReasonBinary            = "binary"
	ReasonGenerated         = "generated"
	ReasonEmpty             = "empty"
)

// Decision is the classifier's verdict for one file.
type Decision struct {
	Path        string
	Disposition Disposition
	Reason      string
	// Detail names the specific rule or threshold, never file contents.
	Detail string
	// Provenance is the taint class assigned at classification (TNT-1, SDD §8). Repository content
	// is untrusted: a file in the tree is authored by whoever could commit to it.
	Provenance taint.Class
	// Generated marks machine-written files. They are indexed but rank lower and are excluded from
	// Next Edit Ripple, since editing one is almost always wrong (NER-5).
	Generated bool
}

// Indexable reports whether contents may be parsed and embedded.
func (d Decision) Indexable() bool { return d.Disposition == DispositionIndex }

// protectedPatterns are paths never indexed, whatever the repository or settings say.
//
// This is deliberately hardcoded rather than settings driven. Every other exclusion here is a
// preference about noise and cost; this one is INV-11. A repository must not be able to opt *into*
// having its deploy keys embedded in a vector index by simply not listing them in `.gitignore`, and
// an administrator must not be able to switch the protection off during an incident.
//
// The list is intentionally narrow: it covers material that is credential-bearing by construction,
// not everything that might be sensitive. Broader policy belongs in settings.
var protectedPatterns = []string{
	"**/.ssh/**",
	"**/.aws/credentials",
	"**/.aws/config",
	"**/.gnupg/**",
	"**/.netrc",
	"**/.npmrc",
	"**/.pypirc",
	"**/.docker/config.json",
	"**/.kube/config",
	"**/id_rsa",
	"**/id_ecdsa",
	"**/id_ed25519",
	"**/*.pem",
	"**/*.key",
	"**/*.p12",
	"**/*.pfx",
	"**/*.keystore",
	"**/*.jks",
	"**/.env",
	"**/.env.*",
	"**/secrets.yaml",
	"**/secrets.yml",
}

// generatedMarkers are byte sequences that identify machine-written files.
//
// The Go convention is the canonical one and is matched exactly as specified; the others are the
// common equivalents from other ecosystems.
var generatedMarkers = [][]byte{
	[]byte("Code generated by"),
	[]byte("DO NOT EDIT"),
	[]byte("@generated"),
	[]byte("autogenerated by"),
	[]byte("This file was automatically generated"),
}

// sniffBytes is how much of a file the classifier reads. It is small on purpose: the classifier
// runs on every file in a monorepo, and the signals it needs — a NUL byte, a generation marker in
// the header — all appear early.
const sniffBytes = 8192

// Config is the resolved settings the classifier operates under.
//
// It is a plain struct rather than a settings.Snapshot so the classifier can be exercised without
// building a snapshot, and so a caller must consciously map each setting across.
type Config struct {
	RespectGitignore bool
	MaxFileBytes     int64
	ExcludedGlobs    []string
}

// ConfigFromSnapshot reads the classifier's settings from a run's frozen snapshot (INV-6).
func ConfigFromSnapshot(snap settings.Snapshot) (Config, error) {
	respect, err := snap.Bool(settings.KeyContextIndexingRespectGitignore)
	if err != nil {
		return Config{}, err
	}
	maxBytes, err := snap.Int(settings.KeyContextIndexingMaxFileBytes)
	if err != nil {
		return Config{}, err
	}
	globs, err := snap.StringList(settings.KeyContextIndexingExcludedGlobs)
	if err != nil {
		return Config{}, err
	}
	return Config{RespectGitignore: respect, MaxFileBytes: maxBytes, ExcludedGlobs: globs}, nil
}

// Classifier decides the disposition of each file in a source tree.
//
// It holds no per-file state and is safe for concurrent use across an indexing fan-out.
type Classifier struct {
	config    Config
	rules     *RuleSet
	protected *RuleSet
}

// NewClassifier returns a Classifier over the resolved config and discovered ignore rules.
func NewClassifier(config Config, rules *RuleSet) (*Classifier, error) {
	if config.MaxFileBytes <= 0 {
		return nil, modberr.New(modberr.CodeSettingInvalid,
			"classifier requires a positive maximum file size").
			WithDetail("setting_key", string(settings.KeyContextIndexingMaxFileBytes))
	}
	if rules == nil {
		rules = NewRuleSet(nil)
	}

	protected := NewRuleSet(nil)
	for _, p := range protectedPatterns {
		parsed, ok := ParsePattern(p, "", SourceSettings)
		if !ok {
			// protectedPatterns is a compile-time constant list; an unparseable entry is a
			// programmer error caught on the first run of any binary linking this package.
			return nil, modberr.Newf(modberr.CodeInternal, "protected pattern %q is not parseable", p)
		}
		protected.Add(parsed)
	}
	for _, g := range config.ExcludedGlobs {
		if parsed, ok := ParsePattern(g, "", SourceSettings); ok {
			rules.Add(parsed)
		}
	}
	return &Classifier{config: config, rules: rules, protected: protected}, nil
}

// File is the metadata the classifier needs about one candidate.
//
// Contents are the first bytes of the file, up to sniffBytes. Passing a prefix rather than a reader
// keeps the classifier pure and keeps CTX-12 obvious: it cannot execute anything, because it never
// holds a handle to anything.
type File struct {
	// Path is repository relative, slash separated.
	Path string
	// Size is the full file size in bytes.
	Size int64
	// Contents is a prefix of the file, at most sniffBytes long. It may be nil when the caller
	// already knows the file is excluded on path or size alone.
	Contents []byte
	// IsDir marks directories, which are matched against directory-only ignore patterns.
	IsDir bool
}

// Classify returns the decision for one file.
//
// Checks run cheapest-first with one deliberate exception: the protected-path check runs before
// everything, including the ignore rules. Ordering it later would mean a `.modbitignore` negation
// could re-include a private key, and the whole point of the protected list is that nothing in the
// repository can override it.
func (c *Classifier) Classify(f File) Decision {
	normalized := normalizePath(f.Path)
	d := Decision{Path: normalized, Provenance: taint.RepositoryUntrusted}

	if v := c.protected.Match(normalized, f.IsDir); v.Ignored {
		d.Disposition = DispositionExclude
		d.Reason = ReasonProtectedPath
		d.Detail = v.Pattern.Raw
		return d
	}

	if v := c.rules.Match(normalized, f.IsDir); v.Ignored {
		// A gitignore rule is honoured only when policy says to. The other ignore sources are
		// Modbit's own and always apply.
		if v.Pattern.Source == SourceGitignore && !c.config.RespectGitignore {
			// Fall through: the repository's build exclusions are not its indexing exclusions here.
		} else {
			d.Disposition = DispositionExclude
			d.Reason = ReasonIgnoreFile
			if v.Pattern.Source == SourceSettings {
				d.Reason = ReasonSettingsExclusion
			}
			d.Detail = string(v.Pattern.Source) + ":" + v.Pattern.Raw
			return d
		}
	}

	if f.IsDir {
		d.Disposition = DispositionIndex
		d.Reason = ReasonIncluded
		return d
	}

	if f.Size == 0 {
		// An empty file has no content to retrieve but its existence is meaningful, so it stays
		// citable rather than disappearing.
		d.Disposition = DispositionReference
		d.Reason = ReasonEmpty
		return d
	}
	if f.Size > c.config.MaxFileBytes {
		d.Disposition = DispositionReference
		d.Reason = ReasonTooLarge
		d.Detail = "exceeds context.indexing.max_file_bytes"
		return d
	}
	if isBinary(f.Contents) {
		d.Disposition = DispositionReference
		d.Reason = ReasonBinary
		return d
	}

	d.Disposition = DispositionIndex
	d.Reason = ReasonIncluded
	if isGenerated(f.Contents) {
		d.Generated = true
		d.Reason = ReasonGenerated
	}
	return d
}

// normalizePath makes a path comparable: slash separated, no leading "./" or "/", cleaned.
func normalizePath(p string) string {
	p = strings.ReplaceAll(p, `\`, "/")
	p = strings.TrimPrefix(p, "./")
	p = strings.TrimPrefix(p, "/")
	if p == "" {
		return p
	}
	return path.Clean(p)
}

// isBinary reports whether a prefix looks like non-text content.
//
// A NUL byte is decisive: no text encoding Modbit indexes contains one. Beyond that, invalid UTF-8
// past a small tolerance means the file is not source in any language the indexer parses. The
// tolerance exists because a truncated sniff can split a multi-byte rune at the boundary.
func isBinary(contents []byte) bool {
	if len(contents) == 0 {
		return false
	}
	if bytes.IndexByte(contents, 0) >= 0 {
		return true
	}
	// Trim a possible partial rune at the end of the sniff window before validating.
	trimmed := contents
	for len(trimmed) > 0 && !utf8.Valid(trimmed) && len(contents)-len(trimmed) < utf8.UTFMax {
		trimmed = trimmed[:len(trimmed)-1]
	}
	return !utf8.Valid(trimmed)
}

// isGenerated reports whether a header carries a generation marker.
//
// Only the first part of the sniff window is searched: the conventions all place the marker in a
// leading comment, and scanning the whole prefix would match any file that merely *discusses*
// generated code.
func isGenerated(contents []byte) bool {
	header := contents
	if len(header) > 2048 {
		header = header[:2048]
	}
	for _, marker := range generatedMarkers {
		if bytes.Contains(header, marker) {
			return true
		}
	}
	return false
}
