package main

import (
	"bytes"
	"fmt"
	"go/format"
	"sort"
	"strings"
)

// generatedGoHeader and generatedTSHeader mark output as machine written. R-CTR-02 forbids editing
// a file carrying this header.
func generatedGoHeader(pkg, source string) string {
	return fmt.Sprintf(`// Code generated by tools/modbitgen from %s. DO NOT EDIT.
//
// Edit the contract and run "make generate". The drift gate in "make check" fails when this file
// is stale.

package %s

`, source, pkg)
}

func generatedTSHeader(source string) string {
	return fmt.Sprintf(`// Code generated by tools/modbitgen from %s. DO NOT EDIT.
//
// Edit the contract and run "make generate".

`, source)
}

func formatGo(path string, src []byte) ([]byte, error) {
	out, err := format.Source(src)
	if err != nil {
		return nil, fmt.Errorf("gofmt %s: %w", path, err)
	}
	return out, nil
}

// initialisms keeps generated Go identifiers idiomatic. Extend deliberately: a name that appears
// here changes every generated symbol containing it.
var initialisms = map[string]string{
	"api":   "API",
	"cpu":   "CPU",
	"dlp":   "DLP",
	"http":  "HTTP",
	"id":    "ID",
	"ir":    "IR",
	"mcp":   "MCP",
	"pr":    "PR",
	"sarif": "SARIF",
	"sdk":   "SDK",
	"ui":    "UI",
	"url":   "URL",
	"vfs":   "VFS",
}

// goIdent converts a dotted, dashed, or underscored contract identifier into an exported Go
// identifier: "run.step.completed" -> "RunStepCompleted", "model.failed_over" -> "ModelFailedOver".
func goIdent(s string) string {
	var b strings.Builder
	for _, word := range splitWords(s) {
		if up, ok := initialisms[word]; ok {
			b.WriteString(up)
			continue
		}
		b.WriteString(strings.ToUpper(word[:1]))
		b.WriteString(word[1:])
	}
	return b.String()
}

func splitWords(s string) []string {
	fields := strings.FieldsFunc(strings.ToLower(s), func(r rune) bool {
		return r == '.' || r == '_' || r == '-' || r == '/'
	})
	out := fields[:0]
	for _, f := range fields {
		if f != "" {
			out = append(out, f)
		}
	}
	return out
}

// tsConstName converts a contract identifier into a SCREAMING_SNAKE TypeScript constant name.
func tsConstName(s string) string {
	return strings.ToUpper(strings.Join(splitWords(s), "_"))
}

// goQuote renders a string as a Go literal, keeping generated output deterministic.
func goQuote(s string) string { return fmt.Sprintf("%q", s) }

// goStringSlice renders a []string literal, preserving contract order.
func goStringSlice(values []string) string {
	if len(values) == 0 {
		return "nil"
	}
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = goQuote(v)
	}
	return "[]string{" + strings.Join(parts, ", ") + "}"
}

// goAnySlice renders a []any literal from YAML scalars (strings, bools, ints).
func goAnySlice(values []any) string {
	if len(values) == 0 {
		return "nil"
	}
	parts := make([]string, len(values))
	for i, v := range values {
		parts[i] = goAnyLiteral(v)
	}
	return "[]any{" + strings.Join(parts, ", ") + "}"
}

// goAnyLiteral renders a YAML scalar or container as a Go literal. Numeric values normalize to
// int64 and float64 so that the generated registry has one representation per JSON number kind.
func goAnyLiteral(v any) string {
	switch t := v.(type) {
	case nil:
		return "nil"
	case string:
		return goQuote(t)
	case bool:
		return fmt.Sprintf("%t", t)
	case int:
		return fmt.Sprintf("int64(%d)", t)
	case int64:
		return fmt.Sprintf("int64(%d)", t)
	case float64:
		if t == float64(int64(t)) {
			return fmt.Sprintf("int64(%d)", int64(t))
		}
		return fmt.Sprintf("float64(%v)", t)
	case []any:
		parts := make([]string, len(t))
		for i, e := range t {
			parts[i] = goAnyLiteral(e)
		}
		return "[]any{" + strings.Join(parts, ", ") + "}"
	case map[string]any:
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys) // deterministic output
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			parts = append(parts, fmt.Sprintf("%s: %s", goQuote(k), goAnyLiteral(t[k])))
		}
		return "map[string]any{" + strings.Join(parts, ", ") + "}"
	default:
		return goQuote(fmt.Sprint(t))
	}
}

// tsLiteral renders a YAML scalar as a TypeScript literal.
func tsLiteral(v any) string {
	switch t := v.(type) {
	case nil:
		return "null"
	case string:
		return goQuote(t)
	case bool:
		return fmt.Sprintf("%t", t)
	case int, int64:
		return fmt.Sprint(t)
	case float64:
		if t == float64(int64(t)) {
			return fmt.Sprint(int64(t))
		}
		return fmt.Sprint(t)
	case []any:
		parts := make([]string, len(t))
		for i, e := range t {
			parts[i] = tsLiteral(e)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case map[string]any:
		keys := make([]string, 0, len(t))
		for k := range t {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		parts := make([]string, 0, len(keys))
		for _, k := range keys {
			parts = append(parts, fmt.Sprintf("%s: %s", goQuote(k), tsLiteral(t[k])))
		}
		return "{ " + strings.Join(parts, ", ") + " }"
	default:
		return goQuote(fmt.Sprint(t))
	}
}

// wrapComment renders text as a sequence of Go or TypeScript line comments at the given indent.
func wrapComment(text, indent string, width int) string {
	text = strings.Join(strings.Fields(text), " ")
	if text == "" {
		return ""
	}
	var b bytes.Buffer
	line := indent + "//"
	for _, word := range strings.Fields(text) {
		if len(line)+1+len(word) > width && line != indent+"//" {
			b.WriteString(line)
			b.WriteByte('\n')
			line = indent + "//"
		}
		line += " " + word
	}
	b.WriteString(line)
	b.WriteByte('\n')
	return b.String()
}
