package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"os"
	"sort"
	"strings"
)

// Error-contract freeze.
//
// The drift gate proves generated code matches the contract. It cannot prove the *contract* only
// ever grew: nothing stops an edit that renames MODBIT_POLICY_DENIED, flips a code's retryability,
// or deletes one outright. Each of those silently breaks every peer, SDK, and stored audit record
// that already carries the old semantics.
//
// The lock file records a digest of each code's wire-visible semantics. `make errors-freeze-check`
// permits additions, and refuses removals and semantic changes.
//
// Rules: R-CTR-04 (additive within a major version), R-CTR-07 (schema versions are immutable),
// R-ERR-01 (stable codes across process boundaries).

const lockHeader = `# Modbit error-contract lock. Generated by tools/modbitgen. DO NOT EDIT.
#
# One line per error code: <code> <sha256 of wire-visible semantics>.
# The digest covers http_status, retryable, and the sorted detail-key allowlist. It deliberately
# excludes the description, which is prose and may be improved.
#
# Adding a code appends a line. Removing or altering one is a breaking change to every peer and to
# every audit record already carrying the old semantics: it requires a new API major version and an
# approved ADR, then a regenerated lock.
`

// semanticDigest hashes the fields a consumer can observe and depend on.
func semanticDigest(e errorCode) string {
	keys := append([]string(nil), e.DetailKeys...)
	sort.Strings(keys)
	h := sha256.New()
	fmt.Fprintf(h, "code=%s\nhttp_status=%d\nretryable=%t\ndeprecated=%t\ndetail_keys=%s\n",
		e.Code, e.HTTPStatus, e.Retryable, e.Deprecated, strings.Join(keys, ","))
	return hex.EncodeToString(h.Sum(nil))
}

func (c *errorCatalog) lockContent() []byte {
	entries := make([]errorCode, len(c.Codes))
	copy(entries, c.Codes)
	sort.Slice(entries, func(i, j int) bool { return entries[i].Code < entries[j].Code })

	var b strings.Builder
	b.WriteString(lockHeader)
	for _, e := range entries {
		fmt.Fprintf(&b, "%s %s\n", e.Code, semanticDigest(e))
	}
	return []byte(b.String())
}

func parseLock(path string) (map[string]string, error) {
	raw, err := os.ReadFile(path)
	if err != nil {
		return nil, err
	}
	out := make(map[string]string)
	for _, line := range strings.Split(string(raw), "\n") {
		line = strings.TrimSpace(line)
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		fields := strings.Fields(line)
		if len(fields) != 2 {
			return nil, fmt.Errorf("malformed lock line: %q", line)
		}
		out[fields[0]] = fields[1]
	}
	return out, nil
}

// checkFreeze compares the catalog against the lock file.
//
// It reports every violation rather than the first, so a contract author fixes one round of
// problems instead of discovering them one CI run at a time.
func (c *errorCatalog) checkFreeze(lockPath string) error {
	locked, err := parseLock(lockPath)
	if err != nil {
		if os.IsNotExist(err) {
			return fmt.Errorf("no error-contract lock at %s; run 'make errors-freeze' to create it", lockPath)
		}
		return err
	}

	current := make(map[string]string, len(c.Codes))
	for _, e := range c.Codes {
		current[e.Code] = semanticDigest(e)
	}

	var violations []string
	for code, digest := range locked {
		got, present := current[code]
		switch {
		case !present:
			violations = append(violations, fmt.Sprintf(
				"%s was removed; error codes are append-only (R-ERR-01). Mark it deprecated instead.", code))
		case got != digest:
			violations = append(violations, fmt.Sprintf(
				"%s changed its wire-visible semantics (http_status, retryable, deprecated, or detail keys). "+
					"Consumers and stored audit records depend on these.", code))
		}
	}

	var added []string
	for code := range current {
		if _, wasLocked := locked[code]; !wasLocked {
			added = append(added, code)
		}
	}
	sort.Strings(added)
	sort.Strings(violations)

	if len(violations) > 0 {
		return fmt.Errorf("error-contract freeze violated:\n  - %s\n\n"+
			"If this change is intended, it needs a new API major version and an approved ADR, "+
			"then 'make errors-freeze' to regenerate the lock.",
			strings.Join(violations, "\n  - "))
	}
	if len(added) > 0 {
		fmt.Printf("errors-freeze-check: %d codes locked, %d added (%s): ok\n",
			len(locked), len(added), strings.Join(added, ", "))
		return nil
	}
	fmt.Printf("errors-freeze-check: %d codes locked, no changes: ok\n", len(locked))
	return nil
}
